/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Kampus(props) {
  const { nodes, materials } = useGLTF('/kampus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text006.geometry}
        material={materials.TExtWhite}
        position={[-9.295, 2.525, -3.172]}
        rotation={[0, -1.518, 0]}
        scale={[1.357, 2.6, 1.807]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text014.geometry}
        material={materials['TExtWhite.001']}
        position={[1.828, 1.76, -8.404]}
        rotation={[0, -1.134, 0]}
        scale={[0.547, 0.596, 0.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text015.geometry}
        material={materials['TExtWhite.007']}
        position={[-0.699, 1.76, -9.099]}
        rotation={[0, -1.134, 0]}
        scale={[1.357, 1.172, 1.807]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text016.geometry}
        material={materials['TExtWhite.008']}
        position={[0.173, 1.753, -7.114]}
        rotation={[0, -1.134, 0]}
        scale={[1.357, 1.172, 1.807]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text017.geometry}
        material={materials['TExtWhite.009']}
        position={[1.178, 1.71, -4.997]}
        rotation={[0, -1.134, 0]}
        scale={[1.357, 1.172, 1.807]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Blue}
        position={[4.746, 0.166, -11.168]}
        rotation={[0, 0.464, 0]}
        scale={[1, 2.183, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Blue}
        position={[6.609, 0.166, -8.57]}
        rotation={[0, 0.464, 0]}
        scale={[1, 2.183, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.Blue}
        position={[7.677, 0.426, -9.273]}
        rotation={[0, 0.464, 0]}
        scale={[1, 2.183, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.Blue}
        position={[7.191, 0.166, -11.168]}
        rotation={[0, 0.464, 0]}
        scale={[1, 2.183, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.Blue}
        position={[7.477, 0.166, -9.448]}
        rotation={[0, 0.464, 0]}
        scale={[1, 2.183, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.Blue}
        position={[7.479, -0.271, -6.497]}
        scale={[1, 2.183, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.Blue}
        position={[8.855, 0.384, -9.122]}
        scale={[1, 2.183, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={materials.Blue}
        position={[1.711, -0.172, -5.182]}
        rotation={[0, 0.436, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={materials.Blue}
        position={[0.747, -0.123, -7.367]}
        rotation={[0, 0.436, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials.Blue}
        position={[-0.159, -0.123, -9.456]}
        rotation={[0, 0.436, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane031.geometry}
        material={materials.Blue}
        position={[3.475, -0.123, -6.202]}
        rotation={[0, 0.436, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={materials.Blue}
        position={[2.559, -0.123, -8.365]}
        rotation={[0, 0.436, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={materials.Blue}
        position={[1.574, -0.123, -10.477]}
        rotation={[0, 0.436, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane034.geometry}
        material={materials.Blue}
        position={[2.577, -0.121, -7.21]}
        rotation={[0, 0.436, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane035.geometry}
        material={materials.Blue}
        position={[1.593, -0.126, -9.378]}
        rotation={[0, 0.436, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane036.geometry}
        material={materials.Blue}
        position={[3.475, -0.123, -6.202]}
        rotation={[0, 0.436, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane041.geometry}
        material={materials.Blue}
        position={[1.742, -0.105, -1.529]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text028.geometry}
        material={materials['TExtWhite.019']}
        position={[0.826, 1.35, -1.087]}
        rotation={[0, -1.134, 0]}
        scale={[0.547, 0.596, 0.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane084.geometry}
        material={materials.Blue}
        position={[-9.103, 0.048, 0.288]}
        rotation={[0, 0.384, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane089.geometry}
        material={materials.Blue}
        position={[-9.103, 0.048, 0.288]}
        rotation={[0, 0.384, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane090.geometry}
        material={materials.Blue}
        position={[-9.103, 0.048, 0.288]}
        rotation={[0, 0.384, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane091.geometry}
        material={materials.Blue}
        position={[-9.103, 0.048, 0.288]}
        rotation={[0, 0.384, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane092.geometry}
        material={materials.Blue}
        position={[-9.103, 0.048, 0.288]}
        rotation={[0, 0.384, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane093.geometry}
        material={materials.Blue}
        position={[-9.103, 0.048, 0.288]}
        rotation={[0, 0.384, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane094.geometry}
        material={materials.Blue}
        position={[-9.103, 0.048, 0.288]}
        rotation={[0, 0.384, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane095.geometry}
        material={materials.Blue}
        position={[-9.103, 0.048, 0.288]}
        rotation={[0, 0.384, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane096.geometry}
        material={materials.Blue}
        position={[-9.103, 0.048, 0.288]}
        rotation={[0, 0.384, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane097.geometry}
        material={materials.Blue}
        position={[-9.103, 0.048, 0.288]}
        rotation={[0, 0.384, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text019.geometry}
        material={materials['TExtWhite.011']}
        position={[5.215, 1.76, -10.188]}
        rotation={[0, -1.134, 0]}
        scale={[1.357, 1.172, 1.807]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials.Pink}
        position={[7.742, 0.01, -3.492]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.Pink}
        position={[11.557, 0.348, -5.313]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials.Pink}
        position={[11.999, 0.01, -4.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials.Pink}
        position={[7.742, 0.01, -3.492]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials.Pink}
        position={[8.526, 0.01, -2.684]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials.Pink}
        position={[8.526, 0.01, -2.684]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials.Pink}
        position={[16.071, 0.348, -5.313]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials.Pink}
        position={[15.769, 0.01, -4.811]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials.Pink}
        position={[16.017, 0.01, -3.498]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials.Pink}
        position={[15.102, 0.009, -6.042]}
        rotation={[-Math.PI, 1.342, -Math.PI]}
        scale={[1, 1, 0.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials.Pink}
        position={[17.95, -0.282, -5.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials.Pink}
        position={[19.061, -0.925, -6.455]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text007.geometry}
        material={materials['TExtWhite.002']}
        position={[12.134, 1.794, -6.067]}
        rotation={[Math.PI, -0.454, Math.PI]}
        scale={[1.357, 1.172, 1.807]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials.LGreen}
        position={[12.999, -0.054, -9.629]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials.LGreen}
        position={[12.64, -0.054, -12.001]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={materials.LGreen}
        position={[13.404, -0.131, -12.245]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials.LGreen}
        position={[13.904, -0.151, -12.501]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={materials.LGreen}
        position={[13.331, -0.304, -13.496]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={materials.LGreen}
        position={[11.861, -0.075, -11.682]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={materials.LGreen}
        position={[12.831, -0.054, -10.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={materials.LGreen}
        position={[16.123, -0.054, -11.421]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane022.geometry}
        material={materials.LGreen}
        position={[15.347, -0.054, -12.787]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane023.geometry}
        material={materials.LGreen}
        position={[14.703, -0.049, -13.884]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={materials.LGreen}
        position={[13.826, -0.054, -14.864]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={materials.LGreen}
        position={[14.237, -0.055, -14.205]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={materials.LGreen}
        position={[15.013, -0.054, -13.321]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials.LGreen}
        position={[15.676, -0.045, -12.241]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text008.geometry}
        material={materials.BlackText}
        position={[12.168, 1.78, -13.28]}
        rotation={[0, -1.134, 0]}
        scale={[0.977, 0.843, 1.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text029.geometry}
        material={materials.BlackText}
        position={[11.761, 1.78, -11.485]}
        rotation={[0, -1.134, 0]}
        scale={[0.977, 0.843, 1.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane037.geometry}
        material={materials['Red.001']}
        position={[-8.035, -0.236, -15.497]}
        rotation={[0, 0.438, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text011.geometry}
        material={materials.BlackText}
        position={[-8.798, 1.49, -15.173]}
        rotation={[0, 0.401, 0]}
        scale={[0.8, 1.172, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials.Path}
        position={[2.243, 0.01, -11.68]}
        scale={0.597}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane057.geometry}
        material={materials.Path}
        position={[2.927, 0.1, -10.239]}
        rotation={[0, 0.438, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane058.geometry}
        material={materials.Path}
        position={[-1.998, 0.1, -1.212]}
        rotation={[-Math.PI, 1.133, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane059.geometry}
        material={materials.Path}
        position={[-1.439, 0.001, -8.206]}
        rotation={[0, 0.438, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane060.geometry}
        material={materials.Path}
        position={[-9.741, 0.1, -8.093]}
        rotation={[0, 0.438, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane061.geometry}
        material={materials['Path.001']}
        position={[2.083, 0.1, 7.841]}
        rotation={[-Math.PI, 1.133, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane062.geometry}
        material={materials['Path.002']}
        position={[12.681, 0.1, -17.584]}
        rotation={[0, 0.438, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane063.geometry}
        material={materials['Path.003']}
        position={[7.156, 1.382, 0.049]}
        rotation={[-Math.PI, 1.133, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane064.geometry}
        material={materials['Path.004']}
        position={[8.984, 0.1, 4.672]}
        rotation={[-Math.PI, 1.133, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane065.geometry}
        material={materials['Path.005']}
        position={[11.4, 0.73, 4.876]}
        rotation={[-Math.PI, 1.133, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane066.geometry}
        material={materials['Path.006']}
        position={[2.777, 0.1, 8.64]}
        rotation={[0, 0.438, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane067.geometry}
        material={materials['Path.007']}
        position={[-0.576, 0.16, -18.409]}
        rotation={[0, 0.438, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane068.geometry}
        material={materials['Path.008']}
        position={[-1.198, 0.1, -10.391]}
        rotation={[-Math.PI, 1.166, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane069.geometry}
        material={materials['Path.009']}
        position={[8.423, 0.1, -14.232]}
        rotation={[0, 0.438, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane070.geometry}
        material={materials['Path.010']}
        position={[7.363, 0.091, -13.714]}
        rotation={[0, 0.438, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane071.geometry}
        material={materials['Path.011']}
        position={[-5.063, 0.1, -14.717]}
        rotation={[0, -0.563, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane072.geometry}
        material={materials['Path.012']}
        position={[1.446, 0.1, -24.313]}
        rotation={[0, -0.608, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane073.geometry}
        material={materials['Path.013']}
        position={[6.807, 0.464, -28.685]}
        rotation={[0, -0.608, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials['Path.014']}
        position={[-12.187, 0.1, -4.246]}
        scale={0.91}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane074.geometry}
        material={materials['Path.015']}
        position={[-15.454, 0.1, -3.049]}
        rotation={[0, -1.209, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane075.geometry}
        material={materials['Path.016']}
        position={[-9.81, 1.59, -7.085]}
        rotation={[0, -0.837, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane076.geometry}
        material={materials['Path.017']}
        position={[-9.135, 1.688, -7.012]}
        rotation={[0, -0.837, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane077.geometry}
        material={materials['Path.018']}
        position={[-11.911, 0.1, 1.093]}
        rotation={[0.018, 0.061, -0.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane078.geometry}
        material={materials['Path.019']}
        position={[-11.911, 0.1, 1.093]}
        rotation={[0.018, 0.061, -0.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane079.geometry}
        material={materials['Path.020']}
        position={[-11.911, 0.1, 1.093]}
        rotation={[0.018, 0.061, -0.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane080.geometry}
        material={materials['Path.021']}
        position={[-11.911, 0.1, 1.093]}
        rotation={[0.018, 0.061, -0.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane081.geometry}
        material={materials['Path.022']}
        position={[-11.911, 0.1, 1.093]}
        rotation={[0.018, 0.061, -0.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane082.geometry}
        material={materials['Path.023']}
        position={[-11.911, 0.1, 1.093]}
        rotation={[0.018, 0.061, -0.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane083.geometry}
        material={materials['Path.024']}
        position={[-1.998, 0.1, -1.212]}
        rotation={[-Math.PI, 1.133, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane085.geometry}
        material={materials['Path.026']}
        position={[-4.627, 0.001, -23.614]}
        rotation={[0, 0.438, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane086.geometry}
        material={materials['Path.027']}
        position={[-10.81, 0.001, -14.997]}
        rotation={[0, 0.438, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane087.geometry}
        material={materials['Path.028']}
        position={[-13.986, 0.1, -18.512]}
        rotation={[0, 0.438, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane088.geometry}
        material={materials['Path.029']}
        position={[-12.917, 0.1, -15.389]}
        rotation={[-Math.PI, 1.166, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials['BlackText.001']}
        position={[-3.97, 0.138, -13.289]}
        rotation={[0, -1.143, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text002.geometry}
        material={materials['BlackText.002']}
        position={[9.426, 0.173, -6.035]}
        rotation={[0, 0.442, 0]}
        scale={[0.78, 1, 0.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text003.geometry}
        material={materials['BlackText.003']}
        position={[2.245, 0.2, -11.116]}
        rotation={[0, -1.131, 0]}
        scale={0.678}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text004.geometry}
        material={materials['BlackText.004']}
        position={[3.644, 0.2, 2.171]}
        rotation={[0, 0.433, 0]}
        scale={0.727}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text005.geometry}
        material={materials['BlackText.006']}
        position={[12.569, 0.204, -17.502]}
        rotation={[0, -1.131, 0]}
        scale={[0.81, 1, 0.74]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text013.geometry}
        material={materials['BlackText.007']}
        position={[-11.561, 0.207, -4.631]}
        rotation={[0, 0.944, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials['Path.030']}
        position={[-5.814, 0.01, 0.887]}
        scale={0.597}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials['Path.031']}
        position={[-5.763, 0.01, 0.752]}
        scale={0.597}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane098.geometry}
        material={materials['Path.032']}
        position={[-5.428, 0.1, 1.493]}
        rotation={[0, 0.438, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text026.geometry}
        material={materials['BlackText.008']}
        position={[-4.03, 0.173, 0.197]}
        rotation={[0, 0.442, 0]}
        scale={[0.78, 1, 0.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text027.geometry}
        material={materials['BlackText.009']}
        position={[1.501, 0.138, -0.978]}
        rotation={[0, -1.143, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane038.geometry}
        material={materials.Puprle}
        position={[0.432, -0.117, 5.788]}
        rotation={[0, 0.41, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane039.geometry}
        material={materials.Puprle}
        position={[0.432, -0.117, 5.788]}
        rotation={[0, 0.41, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane040.geometry}
        material={materials.Puprle}
        position={[0.281, -0.117, 5.841]}
        rotation={[0, -1.117, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text018.geometry}
        material={materials['TExtWhite.010']}
        position={[-0.258, 0.757, 5.368]}
        rotation={[0, -1.134, 0]}
        scale={[0.889, 0.768, 1.184]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane042.geometry}
        material={materials.Brown}
        position={[6.343, 0.1, -16.094]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane043.geometry}
        material={materials.Brown}
        position={[8.628, 0.1, -16.822]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane044.geometry}
        material={materials.Brown}
        position={[8.422, 0.1, -17.538]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane045.geometry}
        material={materials.Brown}
        position={[8.68, 0.336, -18.21]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane046.geometry}
        material={materials.Brown}
        position={[5.497, 0.101, -17.84]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane047.geometry}
        material={materials.Brown}
        position={[7.049, 0.1, -18.681]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane048.geometry}
        material={materials.Brown}
        position={[4.071, 0.1, -14.516]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane049.geometry}
        material={materials.Brown}
        position={[2.974, 0.1, -17.228]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane050.geometry}
        material={materials.Brown}
        position={[5.523, 0.1, -15.767]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane051.geometry}
        material={materials.Brown}
        position={[5.523, 0.1, -15.767]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane052.geometry}
        material={materials.Brown}
        position={[4.798, 0.111, -17.271]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane053.geometry}
        material={materials.Brown}
        position={[3.218, 0.1, -18.704]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane054.geometry}
        material={materials.Brown}
        position={[4.295, 0.1, -19.193]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane055.geometry}
        material={materials.Brown}
        position={[5.387, 0.075, -19.594]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane056.geometry}
        material={materials.Brown}
        position={[5.387, 0.075, -19.594]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text009.geometry}
        material={materials.BlackText}
        position={[4.299, 1.8, -16.558]}
        rotation={[0, 0.401, 0]}
        scale={[1.2, 1.172, 1.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text010.geometry}
        material={materials.BlackText}
        position={[2.632, 1.827, -18.026]}
        rotation={[0, 0.332, 0]}
        scale={[0.8, 1.172, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mapa1001.geometry}
        material={materials.GroundColr}
        position={[0, -0.1, 0]}
        scale={[21.7, 1, 10]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mapa2001.geometry}
        material={materials.GroundColr}
        position={[0, 0, -20]}
        scale={[21.7, 1, 10]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane099.geometry}
        material={materials.VPS}
        position={[4.065, 0.065, -0.008]}
        rotation={[0, 0.419, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane100.geometry}
        material={materials.VPS}
        position={[4.065, 0.065, -0.008]}
        rotation={[0, 0.419, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text020.geometry}
        material={materials.BlackText}
        position={[4.462, 1.14, -0.973]}
        rotation={[0, -1.134, 0]}
        scale={[0.547, 0.596, 0.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane105.geometry}
        material={materials.SDMaterial}
        position={[-1.102, -0.002, -3.241]}
        rotation={[0, 0.436, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane106.geometry}
        material={materials.SDMaterial}
        position={[-2.154, -0.002, -5.322]}
        rotation={[-Math.PI, 1.187, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane108.geometry}
        material={materials.SDMaterial}
        position={[-3.334, -0.002, -2.227]}
        rotation={[0, 0.436, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane107.geometry}
        material={materials.SDMaterial}
        position={[-0.557, -0.002, -1.895]}
        rotation={[-Math.PI, 1.187, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text021.geometry}
        material={materials['TExtWhite.014']}
        position={[-1.514, 1.15, -5.282]}
        rotation={[0, -1.134, 0]}
        scale={[0.547, 0.596, 0.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane101.geometry}
        material={materials.InkognitoMaterijal}
        position={[-1.843, 0.065, 2.855]}
        rotation={[0, 0.611, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane102.geometry}
        material={materials.InkognitoMaterijal}
        position={[-0.821, 0.065, 1.807]}
        rotation={[0, -0.925, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane103.geometry}
        material={materials.InkognitoMaterijal}
        position={[-0.547, 0.065, 0.77]}
        rotation={[Math.PI, -1.414, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane104.geometry}
        material={materials.InkognitoMaterijal}
        position={[-2.467, 0.065, 1.395]}
        rotation={[0, 0.035, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane109.geometry}
        material={materials.SDMaterial}
        position={[-7.304, -0.101, -5.743]}
        rotation={[0, 0.436, 0]}
        scale={[0.808, 1, 0.777]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane110.geometry}
        material={materials.SDMaterial}
        position={[-4.897, -0.101, -4.968]}
        rotation={[-Math.PI, 1.187, -Math.PI]}
        scale={[0.772, 1, 0.807]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane111.geometry}
        material={materials.SDMaterial}
        position={[-5.864, -0.024, -7.843]}
        rotation={[-Math.PI, 1.187, -Math.PI]}
        scale={[0.772, 1, 0.807]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane112.geometry}
        material={materials.SDMaterial}
        position={[-5.411, -0.101, -6.506]}
        rotation={[0, 0.436, 0]}
        scale={[0.808, 1, 0.777]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text022.geometry}
        material={materials['TExtWhite.015']}
        position={[-7.339, 1.15, -6.924]}
        rotation={[0, -1.134, 0]}
        scale={[0.5, 0.596, 0.65]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane113.geometry}
        material={materials.InkognitoMaterijal}
        position={[-1.457, -0.002, -11.831]}
        rotation={[0, 0.436, 0]}
        scale={0.684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane114.geometry}
        material={materials.InkognitoMaterijal}
        position={[0.441, -0.002, -11.604]}
        rotation={[-Math.PI, 1.187, -Math.PI]}
        scale={0.684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane115.geometry}
        material={materials.InkognitoMaterijal}
        position={[-0.65, -0.002, -13.946]}
        rotation={[-Math.PI, 1.187, -Math.PI]}
        scale={0.684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane116.geometry}
        material={materials.InkognitoMaterijal}
        position={[0.069, -0.002, -12.524]}
        rotation={[0, 0.436, 0]}
        scale={0.684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text025.geometry}
        material={materials.BlackText}
        position={[-1.388, 0.78, -13.489]}
        rotation={[0, 0.463, 0]}
        scale={[0.547, 0.596, 0.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane117.geometry}
        material={materials.ZZZSMaterial}
        position={[-2.737, 0.107, -7.444]}
        rotation={[0, 0.436, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane118.geometry}
        material={materials.MenzaMaterial}
        position={[-5.311, 0.107, -9.304]}
        rotation={[0, 1.292, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane119.geometry}
        material={materials.MenzaMaterial}
        position={[-5.378, 0.1, -9.142]}
        rotation={[-0.011, 0.999, -0.004]}
        scale={[0.3, 0.266, 0.328]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane120.geometry}
        material={materials.MenzaMaterial}
        position={[-4.97, 0.253, -10.389]}
        rotation={[-0.011, 0.982, -0.004]}
        scale={[0.3, 0.266, 0.328]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text023.geometry}
        material={materials['TExtWhite.016']}
        position={[-2.794, 1.15, -7.888]}
        rotation={[0, -1.134, 0]}
        scale={[0.547, 0.596, 0.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text024.geometry}
        material={materials['TExtWhite.017']}
        position={[-4.346, 1.2, -9.39]}
        rotation={[0, -Math.PI / 5, 0]}
        scale={[0.547, 0.596, 0.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mapa1.geometry}
        material={materials['Material.001']}
        position={[0, -0.5, 0]}
        scale={[21.7, 1, 10]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mapa2.geometry}
        material={materials['Material.002']}
        position={[0, -0.5, -20]}
        scale={[21.7, 1, 10]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text012.geometry}
        material={materials['BlackText.005']}
        position={[1.839, 0.188, -20.52]}
        rotation={[0, 0.419, 0]}
      />
    </group>
  )
}

useGLTF.preload('/kampus.glb');