/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NastavniBlokUcionice1(props) {
  const { nodes, materials } = useGLTF('/NastavniBlokUcionice1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.MaterialWhite}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ulaz.geometry}
        material={materials.MaterialYellow}
        position={[0.834, 1.101, 0]}
        scale={[0.851, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017'].geometry}
        material={materials.MaterialOrange}
        position={[-4.023, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-4.698, 0.772, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-3.295, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-5.299, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-2.692, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-4.682, 2.158, -0.801]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['002'].geometry}
        material={materials.MaterialOrange}
        position={[17.83, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['002Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[17.124, 0.772, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['002Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[18.066, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['002Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[16.554, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['002Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[18.707, 0.772, -0.824]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['002Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[17.165, 2.158, -0.801]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0211'].geometry}
        material={materials.MaterialOrange}
        position={[-4.023, 1.076, -8.748]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0211Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-4.717, 0.088, -7.743]}
        rotation={[Math.PI / 2, Math.PI / 4, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0211Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-3.498, 0.093, -11.822]}
        rotation={[-Math.PI / 2, Math.PI / 4, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0211Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-5.299, 0.772, -10.523]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0211Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-4.606, 2.158, -8.661]}
        rotation={[0, Math.PI / 4, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairBase.geometry}
        material={materials.MaterialGray}
        position={[-0.664, 1.076, -8.748]}
        scale={[0.331, 1, 0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair.geometry}
        material={materials.MaterialCyan}
        position={[-1.821, 0.197, -8.273]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair001.geometry}
        material={materials['MaterialCyan.001']}
        position={[-1.821, 0.397, -8.573]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair002.geometry}
        material={materials['MaterialCyan.002']}
        position={[-1.821, 0.597, -8.773]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair003.geometry}
        material={materials['MaterialCyan.003']}
        position={[-1.821, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle.geometry}
        material={materials['MaterialCyan.004']}
        position={[-1.821, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair005.geometry}
        material={materials['MaterialCyan.005']}
        position={[0.511, 1.5, -8.494]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair006.geometry}
        material={materials['MaterialCyan.006']}
        position={[0.511, 1.3, -8.694]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair007.geometry}
        material={materials['MaterialCyan.007']}
        position={[0.511, 1.1, -8.994]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle001.geometry}
        material={materials['MaterialCyan.008']}
        position={[-1.821, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle002.geometry}
        material={materials['MaterialCyan.009']}
        position={[0.642, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair004.geometry}
        material={materials['MaterialCyan.010']}
        position={[0.511, 1.7, -8.294]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['021002'].geometry}
        material={materials.MaterialOrange}
        position={[-6.529, 1.076, -8.748]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0212Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-7.17, 0.082, -7.743]}
        rotation={[Math.PI / 2, Math.PI / 4, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0212Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-6.081, 0.077, -11.822]}
        rotation={[-Math.PI / 2, Math.PI / 4, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0212Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-7.805, 0.772, -10.523]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0212Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-5.198, 0.772, -7.896]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0212Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-7.28, 2.158, -8.629]}
        rotation={[0, Math.PI / 4, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['021003'].geometry}
        material={materials.MaterialOrange}
        position={[-9.035, 1.076, -8.748]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0213Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-9.689, 0.032, -7.743]}
        rotation={[Math.PI / 2, Math.PI / 4, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0213Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-8.402, 0.054, -11.822]}
        rotation={[-Math.PI / 2, Math.PI / 4, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0213Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-10.311, 0.772, -10.523]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0213Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-7.704, 0.772, -7.896]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0213Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-9.721, 2.158, -8.524]}
        rotation={[0, Math.PI / 4, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ulaz001.geometry}
        material={materials.MaterialYellow}
        position={[0.446, 1.108, -1.075]}
        scale={[1.209, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.UlazFront.geometry}
        material={materials.MaterialBlack}
        position={[-0.433, 0.805, 1.071]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.946, -0.398, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.UlazBack.geometry}
        material={materials.MaterialBlack}
        position={[1.208, 0.715, -3.107]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.912, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.UlazLeft.geometry}
        material={materials.MaterialBlack}
        position={[-0.77, 0.805, -2.679]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.209, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.UlazRight.geometry}
        material={materials.MaterialBlack}
        position={[1.715, 0.805, 0.497]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.209, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.UlazUpper.geometry}
        material={materials.MaterialBlack}
        position={[-0.374, 2.19, -0.407]}
        scale={[0.946, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC.geometry}
        material={materials.MaterialPink}
        position={[3.447, 1.108, -9.805]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCFront.geometry}
        material={materials.MaterialWhiteText}
        position={[2.229, 0.805, -7.66]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.545, -0.398, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCBack.geometry}
        material={materials.MaterialWhiteText}
        position={[4.692, 0.715, -11.837]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.49, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCRight.geometry}
        material={materials.MaterialWhiteText}
        position={[5.519, 0.805, -8.234]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[2.063, 2.19, -9.137]}
        scale={[1.545, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?'].geometry}
        material={materials.MaterialCyan}
        position={[3.626, 1.108, -1.094]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[2.408, 0.805, 1.052]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.545, -0.398, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[4.871, 0.715, -3.126]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.49, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[1.641, 0.805, -2.698]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[5.698, 0.805, 0.478]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[2.242, 2.19, -0.426]}
        scale={[1.545, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SS.geometry}
        material={materials.MaterialBlue}
        position={[7.473, 1.108, -1.094]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSFront.geometry}
        material={materials.MaterialWhiteText}
        position={[6.167, 0.805, 1.052]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.431, -0.398, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSBack.geometry}
        material={materials.MaterialWhiteText}
        position={[15.984, 0.715, -3.126]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.425, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSLeft.geometry}
        material={materials.MaterialWhiteText}
        position={[5.487, 0.805, -2.698]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSRight.geometry}
        material={materials.MaterialWhiteText}
        position={[9.545, 0.805, 0.478]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[6.423, 2.19, -0.426]}
        scale={[1.348, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Svecana.geometry}
        material={materials.MaterialBlue}
        position={[7.473, 1.108, -9.815]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaFront.geometry}
        material={materials.MaterialWhiteText}
        position={[8.732, 0.805, -7.67]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.431, -0.398, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaBack.geometry}
        material={materials.MaterialWhiteText}
        position={[15.556, 0.715, -11.847]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.425, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaLeft.geometry}
        material={materials.MaterialWhiteText}
        position={[5.487, 0.805, -11.42]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaRight.geometry}
        material={materials.MaterialWhiteText}
        position={[9.545, 0.805, -8.244]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[8.974, 2.19, -9.147]}
        scale={[1.348, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portir001.geometry}
        material={materials.MaterialGray}
        position={[-1.782, 1.113, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PortirFront001.geometry}
        material={materials.MaterialWhiteText}
        position={[-2.715, 0.809, 1.011]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.783, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PortirBack001.geometry}
        material={materials.MaterialWhiteText}
        position={[-1.034, 0.719, -1.005]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.755, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PortirLeft001.geometry}
        material={materials.MaterialWhiteText}
        position={[-2.787, 0.809, -0.952]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PortirRight001.geometry}
        material={materials.MaterialWhiteText}
        position={[-0.732, 0.809, 0.851]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PortirUpper001.geometry}
        material={materials.MaterialWhiteText}
        position={[-2.721, 2.194, 0.336]}
        scale={[0.783, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['007'].geometry}
        material={materials.MaterialOrange}
        position={[-1.782, 1.113, -1.975]}
        scale={[1, 1, 1.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['007Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-2.715, 0.809, -0.957]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.783, 1.007, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['007Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-1.378, 0.719, -3.113]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.755, -1.111, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['007Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-2.787, 0.809, -2.327]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.788, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['007Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-0.732, 0.809, -1.118]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.788, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['007Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-2.166, 2.194, -1.6]}
        scale={[0.783, 1, 1.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016'].geometry}
        material={materials['MaterialOrange.001']}
        position={[-6.542, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-7.217, 0.772, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-5.814, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-7.818, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-5.211, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-7.201, 2.158, -0.801]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['019'].geometry}
        material={materials['MaterialOrange.001']}
        position={[-11.558, 1.076, -8.748]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['019Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.233, 0.772, -7.732]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['019Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-10.83, 0.682, -11.859]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['019Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.834, 0.772, -10.512]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['019Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-10.227, 0.772, -7.885]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['019Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.218, 2.158, -9.512]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018'].geometry}
        material={materials['MaterialOrange.001']}
        position={[-14.072, 1.076, -8.748]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-14.747, 0.772, -7.732]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-14.662, 0.682, -11.859]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.74, 0.772, -7.885]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-14.731, 2.158, -9.512]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018SmallPart'].geometry}
        material={materials['MaterialOrange.003']}
        position={[-16.612, 1.076, -8.748]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['014'].geometry}
        material={materials.MaterialBlue}
        position={[-9.085, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['014Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-9.76, 0.772, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['014Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-9.765, 0.682, -3.099]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.958, 1.103, 1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['014Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-10.361, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['014Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-7.754, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['014Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-9.745, 2.158, -0.801]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['014SmallPart'].geometry}
        material={materials.MaterialBlue}
        position={[-11.625, 1.076, -2.11]}
        scale={[1.269, 1, 0.657]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015'].geometry}
        material={materials.MaterialOrange}
        position={[-14.154, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-14.829, 0.772, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-14.582, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-15.43, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.823, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-14.814, 2.158, -0.801]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015SmallPart'].geometry}
        material={materials.MaterialOrange}
        position={[-16.694, 1.076, -2.11]}
        scale={[1.269, 1, 0.657]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015SmallPart001'].geometry}
        material={materials['MaterialBlue.001']}
        position={[-16.694, 1.076, 0.332]}
        scale={[1.269, 1, 0.657]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013'].geometry}
        material={materials.MaterialYellowGreen}
        position={[-11.625, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.3, 0.772, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-10.897, 0.682, -1.485]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.901, 0.772, -0.839]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-10.294, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.285, 2.158, 0.127]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018A'].geometry}
        material={materials.MaterialYellowGreen}
        position={[-16.625, 1.076, -8.27]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018AFront'].geometry}
        material={materials.MaterialWhiteText}
        position={[-17.3, 0.772, -7.096]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018ABack'].geometry}
        material={materials.MaterialWhiteText}
        position={[-15.897, 0.682, -9.73]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018ALeft'].geometry}
        material={materials.MaterialWhiteText}
        position={[-18.055, 0.772, -9.084]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018AUpper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-17.285, 2.158, -8.119]}
        scale={[0.993, 1, 1]}
      />
    </group>
  )
}

useGLTF.preload('/NastavniBlokUcionice1.glb')

