/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NastavniBlokUcionice6(props) {
  const { nodes, materials } = useGLTF('/NastavniBlokUcionice6.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.MaterialWhite}
        scale={[1, 1, 0.619]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['MaterialWhite.001']}
        position={[35.259, 0, 0]}
        scale={[1, 1, 0.619]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['MaterialWhite.003']}
        position={[31.259, 0, -2.85]}
        scale={[1, 1, 0.619]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairBase.geometry}
        material={materials.MaterialGray}
        position={[-0.664, -0.656, -9.748]}
        scale={[0.331, 1, 0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair.geometry}
        material={materials.MaterialCyan}
        position={[-1.821, -1.535, -9.273]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair001.geometry}
        material={materials['MaterialCyan.001']}
        position={[-1.821, -1.335, -9.573]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair002.geometry}
        material={materials['MaterialCyan.002']}
        position={[-1.821, -1.135, -9.773]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair003.geometry}
        material={materials['MaterialCyan.003']}
        position={[-1.821, -0.935, -9.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle.geometry}
        material={materials['MaterialCyan.004']}
        position={[-1.821, -0.935, -9.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair005.geometry}
        material={materials['MaterialCyan.005']}
        position={[0.511, -0.232, -9.494]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair006.geometry}
        material={materials['MaterialCyan.006']}
        position={[0.511, -0.432, -9.694]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair007.geometry}
        material={materials['MaterialCyan.007']}
        position={[0.511, -0.632, -9.994]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle001.geometry}
        material={materials['MaterialCyan.008']}
        position={[-1.821, -0.935, -9.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle002.geometry}
        material={materials['MaterialCyan.009']}
        position={[0.642, -0.935, -9.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair004.geometry}
        material={materials['MaterialCyan.010']}
        position={[0.511, -0.032, -9.294]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairBase001.geometry}
        material={materials.MaterialGray}
        position={[16.284, -0.7, -2.472]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.15, 1, 0.273]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair008.geometry}
        material={materials.MaterialCyan}
        position={[16.809, -1.578, -2.692]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair009.geometry}
        material={materials['MaterialCyan.001']}
        position={[16.809, -1.378, -2.553]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair010.geometry}
        material={materials['MaterialCyan.002']}
        position={[16.809, -1.178, -2.46]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair011.geometry}
        material={materials['MaterialCyan.003']}
        position={[16.809, -0.978, -2.368]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle003.geometry}
        material={materials['MaterialCyan.004']}
        position={[16.809, -0.978, -2.368]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair012.geometry}
        material={materials['MaterialCyan.005']}
        position={[15.751, -0.276, -2.589]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair013.geometry}
        material={materials['MaterialCyan.006']}
        position={[15.751, -0.476, -2.497]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair014.geometry}
        material={materials['MaterialCyan.007']}
        position={[15.751, -0.676, -2.358]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle004.geometry}
        material={materials['MaterialCyan.008']}
        position={[16.809, -0.978, -2.368]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle005.geometry}
        material={materials['MaterialCyan.009']}
        position={[15.692, -0.978, -2.368]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair015.geometry}
        material={materials['MaterialCyan.010']}
        position={[15.751, -0.076, -2.682]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC.geometry}
        material={materials.MaterialPink}
        position={[7.384, 1.108, -8.82]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCFront.geometry}
        material={materials.MaterialWhiteText}
        position={[6.166, 0.805, -6.675]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.545, -0.398, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCBack.geometry}
        material={materials.MaterialWhiteText}
        position={[8.629, 0.715, -9.222]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.49, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[6, 2.19, -7.174]}
        scale={[1.545, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?'].geometry}
        material={materials.MaterialBlue}
        position={[4.591, 1.108, -3.185]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[3.465, 0.805, -1.04]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.166, -0.398, -0.843]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[5.305, 0.715, -5.217]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.156, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[2.605, 0.805, -4.79]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[6.662, 0.805, -1.614]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[3.506, 2.19, -2.812]}
        scale={[1.118, 1, 1.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?002'].geometry}
        material={materials.MaterialBlue}
        position={[21.703, 1.108, -3.094]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Front002'].geometry}
        material={materials.MaterialWhiteText}
        position={[19.485, 0.805, -0.948]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.906, -0.398, -0.843]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Back002'].geometry}
        material={materials.MaterialWhiteText}
        position={[23.471, 0.715, -9.167]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.908, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Left002'].geometry}
        material={materials.MaterialWhiteText}
        position={[19.718, 0.805, -4.698]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Right002'].geometry}
        material={materials.MaterialWhiteText}
        position={[23.775, 0.805, -2.505]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.29, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Upper002'].geometry}
        material={materials.MaterialWhiteText}
        position={[20.337, 2.19, -5.121]}
        scale={[1.118, 1, 1.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SS.geometry}
        material={materials.MaterialBlue}
        position={[8.778, 1.108, -3.162]}
        scale={[0.798, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSFront.geometry}
        material={materials.MaterialWhiteText}
        position={[9.783, 0.805, -1.017]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.744, -0.398, -0.886]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSBack.geometry}
        material={materials.MaterialWhiteText}
        position={[10.785, 0.715, -5.194]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.739, -2.321, -1.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSLeft.geometry}
        material={materials.MaterialWhiteText}
        position={[9.005, 0.805, -4.766]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSRight.geometry}
        material={materials.MaterialWhiteText}
        position={[9.616, 0.805, -1.591]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[9.702, 2.19, -2.681]}
        scale={[0.784, 0.716, 0.885]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SS001.geometry}
        material={materials.MaterialOrange}
        position={[6.333, 1.108, -3.162]}
        scale={[0.798, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSFront001.geometry}
        material={materials.MaterialWhiteText}
        position={[7.338, 0.805, -1.017]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.744, -0.398, -0.886]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSBack001.geometry}
        material={materials.MaterialWhiteText}
        position={[8.34, 0.715, -5.194]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.739, -2.321, -1.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSLeft001.geometry}
        material={materials.MaterialWhiteText}
        position={[6.559, 0.805, -4.766]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSRight001.geometry}
        material={materials.MaterialWhiteText}
        position={[7.17, 0.805, -1.591]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSUpper001.geometry}
        material={materials.MaterialWhiteText}
        position={[7.257, 2.19, -2.681]}
        scale={[0.784, 0.716, 0.885]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SS002.geometry}
        material={materials.MaterialOrange}
        position={[-0.541, 1.108, -3.162]}
        scale={[0.798, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSFront002.geometry}
        material={materials.MaterialWhiteText}
        position={[0.464, 0.805, -1.017]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.744, -0.398, -0.886]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSBack002.geometry}
        material={materials.MaterialWhiteText}
        position={[1.466, 0.715, -5.194]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.739, -2.321, -1.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSLeft002.geometry}
        material={materials.MaterialWhiteText}
        position={[-0.314, 0.805, -4.766]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSRight002.geometry}
        material={materials.MaterialWhiteText}
        position={[0.297, 0.805, -1.591]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSUpper002.geometry}
        material={materials.MaterialWhiteText}
        position={[0.384, 2.19, -2.681]}
        scale={[0.784, 0.716, 0.885]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SS006.geometry}
        material={materials.MaterialOrange}
        position={[-10.229, 1.108, -3.162]}
        scale={[0.798, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSFront006.geometry}
        material={materials.MaterialWhiteText}
        position={[-9.526, 0.805, -1.017]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.744, -0.398, -0.886]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSBack006.geometry}
        material={materials.MaterialWhiteText}
        position={[-8.474, 0.715, -5.194]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.739, -2.321, -1.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSLeft006.geometry}
        material={materials.MaterialWhiteText}
        position={[-10.003, 0.805, -4.766]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSRight006.geometry}
        material={materials.MaterialWhiteText}
        position={[-9.392, 0.805, -1.591]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSUpper006.geometry}
        material={materials.MaterialWhiteText}
        position={[-9.526, 2.19, -2.681]}
        scale={[0.784, 0.716, 0.885]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SS004.geometry}
        material={materials.MaterialOrange}
        position={[-5.376, 1.108, -3.162]}
        scale={[0.798, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSFront004.geometry}
        material={materials.MaterialWhiteText}
        position={[-4.371, 0.805, -1.017]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.744, -0.398, -0.886]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSBack004.geometry}
        material={materials.MaterialWhiteText}
        position={[-3.369, 0.715, -5.194]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.739, -2.321, -1.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSLeft004.geometry}
        material={materials.MaterialWhiteText}
        position={[-5.15, 0.805, -4.766]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSRight004.geometry}
        material={materials.MaterialWhiteText}
        position={[-4.539, 0.805, -1.591]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSUpper004.geometry}
        material={materials.MaterialWhiteText}
        position={[-4.452, 2.19, -2.681]}
        scale={[0.784, 0.716, 0.885]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SS003.geometry}
        material={materials.MaterialBlue}
        position={[-3, 1.108, -3.162]}
        scale={[0.798, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSFront003.geometry}
        material={materials.MaterialWhiteText}
        position={[-1.995, 0.805, -1.017]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.744, -0.398, -0.886]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSBack003.geometry}
        material={materials.MaterialWhiteText}
        position={[-0.994, 0.715, -5.194]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.739, -2.321, -1.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSLeft003.geometry}
        material={materials.MaterialWhiteText}
        position={[-2.774, 0.805, -4.766]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSRight003.geometry}
        material={materials.MaterialWhiteText}
        position={[-2.163, 0.805, -1.591]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSUpper003.geometry}
        material={materials.MaterialWhiteText}
        position={[-2.076, 2.19, -2.681]}
        scale={[0.784, 0.716, 0.885]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SS005.geometry}
        material={materials.MaterialBlue}
        position={[-7.777, 1.108, -3.162]}
        scale={[0.798, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSFront005.geometry}
        material={materials.MaterialWhiteText}
        position={[-6.772, 0.805, -1.017]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.744, -0.398, -0.886]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSBack005.geometry}
        material={materials.MaterialWhiteText}
        position={[-5.771, 0.715, -5.194]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.739, -2.321, -1.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSLeft005.geometry}
        material={materials.MaterialWhiteText}
        position={[-7.551, 0.805, -4.766]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSRight005.geometry}
        material={materials.MaterialWhiteText}
        position={[-6.94, 0.805, -1.591]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSUpper005.geometry}
        material={materials.MaterialWhiteText}
        position={[-6.853, 2.19, -2.681]}
        scale={[0.784, 0.716, 0.885]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013002'].geometry}
        material={materials.MaterialBlue}
        position={[-15.598, 1.076, -6.058]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front002'].geometry}
        material={materials.MaterialWhiteText}
        position={[-17.12, 0.772, -1.053]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.863, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back002'].geometry}
        material={materials.MaterialWhiteText}
        position={[-11.03, 0.682, -9.123]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right002'].geometry}
        material={materials.MaterialWhiteText}
        position={[-10.267, 0.772, -2.254]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper002'].geometry}
        material={materials.MaterialWhiteText}
        position={[-16.943, 2.158, -5.057]}
        scale={[1.3, 1.434, 1.434]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left001'].geometry}
        material={materials['MaterialWhiteText.001']}
        position={[-18.053, 0.772, -7.599]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013001'].geometry}
        material={materials.MaterialYellowGreen}
        position={[-8.973, 1.076, -7.747]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper001'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[-10.256, 2.152, -7.651]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right003'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[-8.256, 0.772, -7.282]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front001'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[-10.296, 0.772, -6.698]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back001'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[-8.39, 0.682, -9.199]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013005'].geometry}
        material={materials.MaterialYellowGreen}
        position={[2.788, 1.076, -7.765]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper005'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[1.718, 2.152, -7.67]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right004'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[3.505, 0.772, -7.301]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front005'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[1.717, 0.772, -6.717]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back005'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[3.223, 0.682, -9.218]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left'].geometry}
        material={materials['MaterialWhiteText.004']}
        position={[1.448, 0.772, -8.634]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-0.783, -1.269, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013006'].geometry}
        material={materials.MaterialOrange}
        position={[4.75, 1.076, -7.765]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper006'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[3.452, 2.152, -7.67]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right005'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[5.467, 0.772, -7.301]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front006'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[3.554, 0.772, -6.717]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.893, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back006'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[5.331, 0.682, -9.218]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left002'].geometry}
        material={materials['MaterialWhiteText.004']}
        position={[3.41, 0.772, -8.634]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-0.783, -1.269, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013007'].geometry}
        material={materials.MaterialYellowGreen}
        position={[10.831, 1.076, -7.765]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper007'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[9.761, 2.152, -7.67]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right006'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[11.548, 0.772, -7.301]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front007'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[9.76, 0.772, -6.717]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back007'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[11.266, 0.682, -9.218]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left003'].geometry}
        material={materials['MaterialWhiteText.004']}
        position={[9.491, 0.772, -8.634]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-0.783, -1.269, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013010'].geometry}
        material={materials.MaterialYellowGreen}
        position={[16.727, 1.076, -7.765]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper009'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[15.658, 2.152, -7.67]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right009'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[17.444, 0.772, -7.301]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front009'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[15.656, 0.772, -6.717]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back009'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[17.163, 0.682, -9.218]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left006'].geometry}
        material={materials['MaterialWhiteText.004']}
        position={[15.387, 0.772, -8.634]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-0.783, -1.269, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013011'].geometry}
        material={materials.MaterialOrange}
        position={[18.696, 1.076, -7.765]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper010'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[17.627, 2.152, -7.67]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right010'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[19.413, 0.772, -7.301]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front010'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[17.625, 0.772, -6.717]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back010'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[19.131, 0.682, -9.218]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left007'].geometry}
        material={materials['MaterialWhiteText.004']}
        position={[17.356, 0.772, -8.634]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-0.783, -1.269, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013012'].geometry}
        material={materials.MaterialOrange}
        position={[18.696, 1.076, -2.063]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper011'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[18.5, 2.152, -3.392]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right011'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[19.413, 0.772, -1.599]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front011'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[19.177, 0.409, -1.015]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back011'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[18.5, 0.417, -4.477]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left008'].geometry}
        material={materials['MaterialWhiteText.004']}
        position={[17.356, 0.772, -2.932]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-0.783, -1.269, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013013'].geometry}
        material={materials.MaterialYellowGreen}
        position={[17.736, 1.076, -2.063]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper012'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[17.541, 2.152, -3.406]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right012'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[18.454, 0.772, -1.599]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front012'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[18.218, 0.409, -1.015]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back012'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[17.54, 0.417, -4.474]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013008'].geometry}
        material={materials.MaterialOrange}
        position={[12.788, 1.076, -7.765]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper008'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[12.718, 2.152, -7.67]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right007'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[13.505, 0.772, -7.301]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front008'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[12.717, 0.772, -6.717]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back008'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[14.135, 0.682, -9.218]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left004'].geometry}
        material={materials['MaterialWhiteText.004']}
        position={[11.448, 0.772, -8.634]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-0.783, -1.269, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013014'].geometry}
        material={materials.MaterialOrange}
        position={[12.788, 1.076, -2.104]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper003'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[12.718, 2.152, -2.397]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right014'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[13.505, 0.772, -1.64]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front003'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[12.717, 0.772, -1.056]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back003'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[14.135, 0.682, -4.53]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left010'].geometry}
        material={materials['MaterialWhiteText.004']}
        position={[11.448, 0.772, -2.973]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-0.783, -1.269, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013009'].geometry}
        material={materials.MaterialOrange}
        position={[14.75, 1.076, -2.094]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right008'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[15.312, 0.772, -1.63]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left005'].geometry}
        material={materials['MaterialWhiteText.004']}
        position={[13.41, 0.772, -2.962]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-0.783, -1.269, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013003'].geometry}
        material={materials.MaterialOrange}
        position={[14.75, 1.076, -7.765]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right013'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[15.467, 0.772, -7.301]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left009'].geometry}
        material={materials['MaterialWhiteText.004']}
        position={[13.41, 0.772, -8.634]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-0.783, -1.269, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013004'].geometry}
        material={materials.MaterialOrange}
        position={[-7.003, 1.076, -7.747]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper004'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[-6.286, 2.152, -7.651]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right001'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[-2.638, 0.772, -7.403]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front004'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[-6.325, 0.772, -6.698]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back004'].geometry}
        material={materials['MaterialWhiteText.003']}
        position={[-4.905, 0.682, -9.199]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
    </group>
  )
}

useGLTF.preload('/NastavniBlokUcionice6.glb')

