/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NastavniBlok1(props) {
  const { nodes, materials } = useGLTF('/NastavniBlok1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kafe.geometry}
        material={materials.MaterialYellowGreen}
        position={[-1.376, 0.251, 0.457]}
        scale={[0.299, 0.153, 0.118]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.UlazHol.geometry}
        material={materials.MaterialWhite}
        scale={[1.684, 0.105, 1.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DugackiHodnik.geometry}
        material={materials.MaterialWhite}
        position={[0.682, 0, 2.587]}
        scale={[1, 0.105, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GridDeo.geometry}
        material={materials.MaterialWhite}
        position={[-0.806, 0, 6.537]}
        scale={[2.491, 0.105, 0.676]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.VrataUlazna.geometry}
        material={materials.MaterialYellow}
        position={[1.468, 0.251, -0.009]}
        scale={[0.208, 0.153, 0.532]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.VrataUlaznaFront.geometry}
        material={materials.MaterialBlack}
        position={[1.683, 0.267, -0.006]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.191, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Protir.geometry}
        material={materials.MaterialGray}
        position={[1.468, 0.251, -1.038]}
        scale={[0.208, 0.153, 0.245]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PortirFront.geometry}
        material={materials.MaterialWhiteText}
        position={[1.69, 0.267, -0.888]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.195, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ScenDizajn.geometry}
        material={materials.MaterialBlue}
        position={[-0.165, 0.251, -0.769]}
        scale={[0.937, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Biblioteka.geometry}
        material={materials.MaterialBlue}
        position={[-0.182, 0.251, 1.075]}
        scale={[0.937, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B008.geometry}
        material={materials.MaterialOrange}
        position={[0.558, 0.251, 1.075]}
        scale={[0.201, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B001001.geometry}
        material={materials.MaterialOrange}
        position={[1.474, 0.251, 0.657]}
        scale={[0.207, 0.153, 0.137]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B002001.geometry}
        material={materials.MaterialOrange}
        position={[1.474, 0.251, 0.933]}
        scale={[0.207, 0.153, 0.137]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B003001.geometry}
        material={materials.MaterialOrange}
        position={[1.474, 0.251, 1.208]}
        scale={[0.207, 0.153, 0.137]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B004.geometry}
        material={materials.MaterialOrange}
        position={[1.474, 0.251, 1.484]}
        scale={[0.207, 0.153, 0.137]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HodnikSkriptarnica.geometry}
        material={materials.MaterialWhite}
        position={[0.634, 0, -2.51]}
        scale={[0.699, 0.105, 0.369]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Skriptarnica.geometry}
        material={materials.MaterialBlue}
        position={[1.01, 0.251, -2.09]}
        scale={[0.328, 0.153, 0.798]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B005001.geometry}
        material={materials.MaterialOrange}
        position={[1.474, 0.251, 1.687]}
        scale={[0.207, 0.153, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B006001.geometry}
        material={materials.MaterialOrange}
        position={[1.474, 0.251, 1.827]}
        scale={[0.207, 0.153, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B007.geometry}
        material={materials.MaterialOrange}
        position={[1.214, 0.251, 2.228]}
        scale={[0.465, 0.153, 0.328]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC1.geometry}
        material={materials.MaterialPink}
        position={[1.214, 0.251, 2.875]}
        scale={[0.465, 0.153, 0.328]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC1HODNIK.geometry}
        material={materials.MaterialPink}
        position={[0.957, 0.251, 3.61]}
        scale={[0.198, 0.153, 0.427]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KodWCUcionica.geometry}
        material={materials.MaterialOrange}
        position={[1.214, 0.251, 4.363]}
        scale={[0.465, 0.153, 0.328]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GR1.geometry}
        material={materials['Material.030']}
        position={[1.214, 0.251, 5.246]}
        scale={[0.465, 0.153, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC2.geometry}
        material={materials.MaterialPink}
        position={[1.214, 0.251, 6.38]}
        scale={[0.465, 0.153, 0.527]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GR2.geometry}
        material={materials.MaterialBlue}
        position={[-1.212, 0.251, 6.52]}
        scale={[2.09, 0.153, 0.676]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ProstorijaKodStepenica.geometry}
        material={materials.MaterialBlue}
        position={[-1.428, 0.251, -1.069]}
        scale={[0.256, 0.153, 0.219]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KodWCUcionica2.geometry}
        material={materials.MaterialOrange}
        position={[1.214, 0.251, 7.062]}
        scale={[0.465, 0.153, 0.145]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.VrataUlaznaUpper.geometry}
        material={materials.MaterialBlack}
        position={[1.477, 0.408, -0.006]}
        rotation={[0, 1.571, 0]}
        scale={[0.191, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B002Front.geometry}
        material={materials.MaterialWhiteText}
        position={[1.692, 0.267, 0.932]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.143, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B001Front.geometry}
        material={materials.MaterialWhiteText}
        position={[1.692, 0.267, 0.661]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.143, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B003Front.geometry}
        material={materials.MaterialWhiteText}
        position={[1.692, 0.267, 1.208]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.143, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B004Front.geometry}
        material={materials.MaterialWhiteText}
        position={[1.692, 0.267, 1.477]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.143, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B005Front.geometry}
        material={materials.MaterialWhiteText}
        position={[1.692, 0.267, 1.686]}
        rotation={[3.138, 0, -Math.PI / 2]}
        scale={[0.143, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B006Front.geometry}
        material={materials.MaterialWhiteText}
        position={[1.692, 0.267, 1.827]}
        rotation={[3.135, 0, -Math.PI / 2]}
        scale={[0.143, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B001Upper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.482, 0.407, 0.648]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.143, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B002Upper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.482, 0.407, 0.94]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.143, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B003Upper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.482, 0.407, 1.209]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.143, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B004Upper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.482, 0.407, 1.479]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.143, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B005Upper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.482, 0.407, 1.677]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.085, 0.092, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B006Upper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.482, 0.407, 1.832]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.085, 0.092, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B007Front.geometry}
        material={materials.MaterialWhiteText}
        position={[1.692, 0.267, 2.217]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.22, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B007Upper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.249, 0.407, 2.227]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.273, 0.296, 0.296]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC1Front.geometry}
        material={materials.MaterialWhiteText}
        position={[1.692, 0.254, 2.874]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.22, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC1Upper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.224, 0.407, 2.873]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.273, 0.296, 0.296]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PortirUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.477, 0.408, -0.901]}
        rotation={[0, 1.571, 0]}
        scale={[0.191, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SkriptarnicaFront.geometry}
        material={materials.MaterialWhiteText}
        position={[1.339, 0.267, -2.086]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.195, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SkriptarnicaUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.018, 0.408, -2.117]}
        rotation={[0, 1.571, 0]}
        scale={[0.254, 0.247, 0.247]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GR1Front.geometry}
        material={materials.MaterialWhiteText}
        position={[1.692, 0.254, 5.239]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.22, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GR1Upper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.224, 0.407, 5.253]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.263, 0.285, 0.285]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC2Front.geometry}
        material={materials.MaterialWhiteText}
        position={[1.68, 0.254, 6.407]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.22, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC2Upper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.224, 0.407, 6.413]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.273, 0.296, 0.296]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PortirBack.geometry}
        material={materials.MaterialWhiteText}
        position={[1.254, 0.204, -1.152]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={0.209}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.VrataUlaznaBack.geometry}
        material={materials.MaterialBlack}
        position={[1.254, 0.204, -0.194]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={0.209}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B001Back.geometry}
        material={materials.MaterialWhiteText}
        position={[1.254, 0.204, 0.548]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={0.152}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B002Back.geometry}
        material={materials.MaterialWhiteText}
        position={[1.254, 0.204, 0.809]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={0.152}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B003Back.geometry}
        material={materials.MaterialWhiteText}
        position={[1.254, 0.204, 1.091]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={0.152}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B004Back.geometry}
        material={materials.MaterialWhiteText}
        position={[1.254, 0.204, 1.357]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={0.152}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B005Back.geometry}
        material={materials.MaterialWhiteText}
        position={[1.254, 0.149, 1.736]}
        rotation={[0, -0.009, Math.PI / 2]}
        scale={0.135}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B006Back.geometry}
        material={materials.MaterialWhiteText}
        position={[1.254, 0.149, 1.873]}
        rotation={[0, -0.009, Math.PI / 2]}
        scale={0.135}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B007Back.geometry}
        material={materials.MaterialWhiteText}
        position={[0.737, 0.178, 2.012]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.291, 0.183, 0.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC1Back.geometry}
        material={materials.MaterialWhiteText}
        position={[0.737, 0.178, 3.046]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.291, 0.183, 0.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GR1Back.geometry}
        material={materials.MaterialWhiteText}
        position={[0.737, 0.178, 4.886]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.291, 0.183, 0.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SkriptarnicaBack.geometry}
        material={materials.MaterialWhiteText}
        position={[0.67, 0.178, -2.622]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={0.235}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ScenDizajnFront.geometry}
        material={materials['Material.001']}
        position={[0.786, 0.267, -0.776]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.195, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ScenDizajnUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[-0.229, 0.408, -0.756]}
        rotation={[-Math.PI, 0.354, -Math.PI]}
        scale={[0.313, 0.304, 0.304]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B008Front.geometry}
        material={materials.MaterialWhiteText}
        position={[0.786, 0.267, 1.091]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.195, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B008Upper.geometry}
        material={materials.MaterialWhiteText}
        position={[0.558, 0.407, 1.088]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.233, 0.253, 0.253]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BibliotekaUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[-0.598, 0.408, 1.011]}
        rotation={[-Math.PI, 0.354, -Math.PI]}
        scale={[0.313, 0.304, 0.304]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GR2Upper.geometry}
        material={materials.MaterialWhiteText}
        position={[-1.392, 0.407, 6.544]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.386, 0.285, 0.346]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B008Right.geometry}
        material={materials['Material.013']}
        position={[0.564, 0.25, 0.557]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.195, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BibliotekaRight.geometry}
        material={materials['Material.018']}
        position={[-0.335, 0.25, 0.557]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.195, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ScenDizajnRight.geometry}
        material={materials['Material.020']}
        position={[-0.335, 0.25, -1.291]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.195, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SkriptarnicaRight.geometry}
        material={materials['Material.021']}
        position={[1.016, 0.25, -2.889]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.121, 0.186, 0.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GR2Right.geometry}
        material={materials.MaterialWhiteText}
        position={[-1.386, 0.25, 5.833]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.267, 0.186, 0.213]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PortirRight.geometry}
        material={materials['Material.023']}
        position={[1.498, 0.25, -1.291]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.121, 0.186, 0.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B007Right.geometry}
        material={materials.MaterialWhiteText}
        position={[1.017, 0.25, 1.889]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.166, 0.255, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ProstorijaKodStepenicaRight.geometry}
        material={materials['Material.025']}
        position={[-1.519, 0.24, -1.291]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.245, 0.233, 0.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ProstorijaKodStepenicaBack.geometry}
        material={materials.MaterialWhiteText}
        position={[-1.688, 0.162, -1.114]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={0.235}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ProstorijaKodStepenicaUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[-1.492, 0.408, -1.08]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.293, 0.285, 0.285]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ScenDizajnLeft.geometry}
        material={materials.MaterialWhiteText}
        position={[-0.258, 0.248, -0.246]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.242, 0.203, 0.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ProstorijaKodStepenicaLeft.geometry}
        material={materials['Material.031']}
        position={[-1.523, 0.248, -0.838]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.242, 0.203, 0.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BibliotekaLeft.geometry}
        material={materials.MaterialWhiteText}
        position={[-0.673, 0.248, 1.6]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.242, 0.203, 0.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GR2Left.geometry}
        material={materials.MaterialWhiteText}
        position={[-1.38, 0.248, 7.227]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.272, 0.203, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ScenDizajnBack.geometry}
        material={materials.MaterialWhiteText}
        position={[-1.337, 0.162, -0.778]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={0.235}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GR2Back.geometry}
        material={materials.MaterialWhiteText}
        position={[-3.311, 0.186, 6.108]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.291, 0.183, 0.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ProstorijaKodStepenicaBack001.geometry}
        material={materials.MaterialWhiteText}
        position={[-1.688, 0.112, 0.497]}
        rotation={[0, -0.009, Math.PI / 2]}
        scale={0.166}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KafaFront.geometry}
        material={materials.MaterialWhiteText}
        position={[-1.073, 0.256, 0.455]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
        scale={[0.164, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KafaLeft.geometry}
        material={materials.MaterialWhiteText}
        position={[-1.338, 0.24, 0.332]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.245, 0.233, 0.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BibliotekaBack.geometry}
        material={materials.MaterialWhiteText}
        position={[-1.688, 0.162, 0.603]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.162, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KodWCUcionicaFront.geometry}
        material={materials.MaterialWhiteText}
        position={[1.692, 0.254, 4.389]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.22, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KodWCUcionicaBack.geometry}
        material={materials.MaterialWhiteText}
        position={[0.744, 0.254, 4.389]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[-0.255, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KodWcUcionicaRight.geometry}
        material={materials['Material.066']}
        position={[1.428, 0.25, 4.031]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.121, 0.186, 0.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KodWCUcionicaUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.224, 0.407, 4.39]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.263, 0.285, 0.285]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KodWCUcionica2Front.geometry}
        material={materials.MaterialWhiteText}
        position={[1.692, 0.254, 7.075]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.22, 0.155, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KodWCUcionica2Left.geometry}
        material={materials.MaterialWhiteText}
        position={[1.214, 0.248, 7.227]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.242, 0.203, 0.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KodWCUcionica2Upper.geometry}
        material={materials.MaterialWhiteText}
        position={[1.23, 0.407, 7.055]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.273, 0.296, 0.258]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B008Left.geometry}
        material={materials.MaterialWhiteText}
        position={[0.552, 0.25, 1.593]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[-0.198, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KafaUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[-1.395, 0.407, 0.446]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.233, 0.253, 0.23]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair.geometry}
        material={materials.MaterialCyan}
        position={[1.419, 0.136, 3.61]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair001.geometry}
        material={materials.MaterialCyan}
        position={[1.419, 0.157, 3.56]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair002.geometry}
        material={materials.MaterialCyan}
        position={[1.419, 0.187, 3.51]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair003.geometry}
        material={materials.MaterialCyan}
        position={[1.419, 0.217, 3.46]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair004.geometry}
        material={materials.MaterialCyan}
        position={[1.419, 0.247, 3.41]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair005.geometry}
        material={materials.MaterialCyan}
        position={[1.419, 0.277, 3.36]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair006.geometry}
        material={materials.MaterialCyan}
        position={[1.419, 0.307, 3.31]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair007.geometry}
        material={materials.MaterialCyan}
        position={[1.419, 0.337, 3.26]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair008.geometry}
        material={materials.MaterialCyan}
        position={[1.419, 0.367, 3.21]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair009.geometry}
        material={materials.MaterialCyan}
        position={[-1.225, 0.136, 0.072]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair010.geometry}
        material={materials.MaterialCyan}
        position={[-1.275, 0.157, 0.072]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair011.geometry}
        material={materials.MaterialCyan}
        position={[-1.325, 0.187, 0.072]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair012.geometry}
        material={materials.MaterialCyan}
        position={[-1.375, 0.217, 0.072]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair013.geometry}
        material={materials.MaterialCyan}
        position={[-1.425, 0.247, 0.072]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair014.geometry}
        material={materials.MaterialCyan}
        position={[-1.475, 0.277, 0.072]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair015.geometry}
        material={materials.MaterialCyan}
        position={[-1.525, 0.307, 0.072]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair016.geometry}
        material={materials.MaterialCyan}
        position={[-1.575, 0.337, 0.072]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair017.geometry}
        material={materials.MaterialCyan}
        position={[-1.625, 0.367, 0.072]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
    </group>
  )
}

useGLTF.preload('/NastavniBlok1.glb')