/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NastavniBlokUcionice4(props) {
  const { nodes, materials } = useGLTF('/NastavniBlokUcionice4.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.MaterialWhite}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017'].geometry}
        material={materials.MaterialYellowGreen}
        position={[-4.023, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-5.244, 0.772, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-1.973, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-5.299, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-2.692, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-5.192, 2.158, -0.801]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017001'].geometry}
        material={materials.MaterialOrange}
        position={[-0.581, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Front001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-1.014, 0.772, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Back001'].geometry}
        material={materials.MaterialWhiteText}
        position={[0.827, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Left001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-1.857, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Right001'].geometry}
        material={materials.MaterialWhiteText}
        position={[0.75, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Upper001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-1.018, 2.158, -0.801]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairBase.geometry}
        material={materials.MaterialGray}
        position={[-0.664, 1.076, -8.748]}
        scale={[0.331, 1, 0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair.geometry}
        material={materials.MaterialCyan}
        position={[-1.821, 0.197, -8.273]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair001.geometry}
        material={materials['MaterialCyan.001']}
        position={[-1.821, 0.397, -8.573]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair002.geometry}
        material={materials['MaterialCyan.002']}
        position={[-1.821, 0.597, -8.773]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair003.geometry}
        material={materials['MaterialCyan.003']}
        position={[-1.821, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle.geometry}
        material={materials['MaterialCyan.004']}
        position={[-1.821, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair005.geometry}
        material={materials['MaterialCyan.005']}
        position={[0.511, 1.5, -8.494]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair006.geometry}
        material={materials['MaterialCyan.006']}
        position={[0.511, 1.3, -8.694]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair007.geometry}
        material={materials['MaterialCyan.007']}
        position={[0.511, 1.1, -8.994]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle001.geometry}
        material={materials['MaterialCyan.008']}
        position={[-1.821, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle002.geometry}
        material={materials['MaterialCyan.009']}
        position={[0.642, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair004.geometry}
        material={materials['MaterialCyan.010']}
        position={[0.511, 1.7, -8.294]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC.geometry}
        material={materials.MaterialPink}
        position={[3.447, 1.108, -9.805]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCFront.geometry}
        material={materials.MaterialWhiteText}
        position={[2.229, 0.805, -7.66]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.545, -0.398, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCBack.geometry}
        material={materials.MaterialWhiteText}
        position={[4.692, 0.715, -11.837]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.49, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCRight.geometry}
        material={materials.MaterialWhiteText}
        position={[5.519, 0.805, -8.234]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[2.063, 2.19, -9.137]}
        scale={[1.545, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?'].geometry}
        material={materials.MaterialOrange}
        position={[3.626, 1.108, -1.094]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[2.732, 0.805, 1.052]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.166, -0.398, -0.843]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[4.674, 0.715, -3.126]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.49, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[1.641, 0.805, -2.698]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[5.698, 0.805, 0.478]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[2.851, 2.19, -0.72]}
        scale={[1.118, 1, 1.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?001'].geometry}
        material={materials.MaterialOrange}
        position={[12.02, 1.108, -1.094]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Front001'].geometry}
        material={materials.MaterialWhiteText}
        position={[11.125, 0.805, 1.052]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.166, -0.398, -0.843]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Back001'].geometry}
        material={materials.MaterialWhiteText}
        position={[13.068, 0.715, -3.126]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.49, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Left001'].geometry}
        material={materials.MaterialWhiteText}
        position={[10.034, 0.805, -2.698]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Right001'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.091, 0.805, 0.478]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Upper001'].geometry}
        material={materials.MaterialWhiteText}
        position={[11.244, 2.19, -0.72]}
        scale={[1.118, 1, 1.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?003'].geometry}
        material={materials.MaterialOrange}
        position={[12.02, 1.108, -9.81]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Front003'].geometry}
        material={materials.MaterialWhiteText}
        position={[11.125, 0.805, -7.665]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.166, -0.398, -0.843]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Back003'].geometry}
        material={materials.MaterialWhiteText}
        position={[13.068, 0.715, -11.842]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.49, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Left003'].geometry}
        material={materials.MaterialWhiteText}
        position={[10.034, 0.805, -11.415]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Right003'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.091, 0.805, -8.239]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Upper003'].geometry}
        material={materials.MaterialWhiteText}
        position={[11.244, 2.19, -9.437]}
        scale={[1.118, 1, 1.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?002'].geometry}
        material={materials.MaterialBlue}
        position={[16.703, 1.108, -1.094]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Front002'].geometry}
        material={materials.MaterialWhiteText}
        position={[15.689, 0.805, 1.052]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.166, -0.398, -0.843]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Back002'].geometry}
        material={materials.MaterialWhiteText}
        position={[17.751, 0.715, -3.126]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.49, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Left002'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.718, 0.805, -2.698]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Right002'].geometry}
        material={materials.MaterialWhiteText}
        position={[18.775, 0.805, -0.091]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.29, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Upper002'].geometry}
        material={materials.MaterialWhiteText}
        position={[15.796, 2.19, -0.72]}
        scale={[1.118, 1, 1.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?004'].geometry}
        material={materials.MaterialBlue}
        position={[16.703, 1.108, -9.801]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Front004'].geometry}
        material={materials.MaterialWhiteText}
        position={[15.689, 0.805, -7.656]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.166, -0.398, -0.843]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Back004'].geometry}
        material={materials.MaterialWhiteText}
        position={[17.751, 0.715, -11.833]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.49, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Left004'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.718, 0.805, -11.406]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Right004'].geometry}
        material={materials.MaterialWhiteText}
        position={[18.775, 0.805, -8.798]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.29, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Upper004'].geometry}
        material={materials.MaterialWhiteText}
        position={[15.796, 2.19, -9.428]}
        scale={[1.118, 1, 1.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SS.geometry}
        material={materials.MaterialBlue}
        position={[6.354, 1.108, -1.094]}
        scale={[0.798, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSFront.geometry}
        material={materials.MaterialWhiteText}
        position={[7.152, 0.805, 1.052]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.959, -0.398, -0.886]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSBack.geometry}
        material={materials.MaterialWhiteText}
        position={[8.767, 0.715, -3.126]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.038, -2.321, -1.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSLeft.geometry}
        material={materials.MaterialWhiteText}
        position={[5.551, 0.805, -2.698]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSRight.geometry}
        material={materials.MaterialWhiteText}
        position={[7.191, 0.805, 0.478]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[7.132, 2.19, -0.74]}
        scale={[1.095, 1, 1.236]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SS001.geometry}
        material={materials.MaterialBlue}
        position={[6.354, 1.108, -9.812]}
        scale={[0.798, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSFront001.geometry}
        material={materials.MaterialWhiteText}
        position={[7.152, 0.805, -7.667]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.959, -0.398, -0.886]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSBack001.geometry}
        material={materials.MaterialWhiteText}
        position={[8.767, 0.715, -11.844]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.038, -2.321, -1.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSLeft001.geometry}
        material={materials.MaterialWhiteText}
        position={[5.551, 0.805, -11.416]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSRight001.geometry}
        material={materials.MaterialWhiteText}
        position={[7.191, 0.805, -8.241]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSUpper001.geometry}
        material={materials.MaterialWhiteText}
        position={[7.132, 2.19, -9.458]}
        scale={[1.095, 1, 1.236]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016'].geometry}
        material={materials.MaterialBlue}
        position={[-6.542, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-7.818, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-5.211, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['014'].geometry}
        material={materials.MaterialBlue}
        position={[-9.085, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['014Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-9.218, 0.772, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['014Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-6.264, 0.682, -3.099]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.958, 1.103, 1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['014Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-10.361, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['014Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-7.754, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['014Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-9.343, 2.158, -0.801]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015'].geometry}
        material={materials.MaterialOrange}
        position={[-14.154, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-16.829, 0.772, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-13.838, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-15.43, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.823, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-16.975, 2.158, -0.801]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015001'].geometry}
        material={materials.MaterialOrange}
        position={[-4.03, 1.076, -8.743]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Front001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-8.096, 0.772, -7.739]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Back001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-4.94, 0.682, -11.817]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Left001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-5.306, 0.772, -10.519]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Upper001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-8.104, 2.158, -9.519]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013'].geometry}
        material={materials.MaterialYellowGreen}
        position={[-11.625, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.57, 0.772, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-10.647, 0.682, -3.09]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-18.053, 0.772, -2.273]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-10.294, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.551, 2.158, -0.69]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013001'].geometry}
        material={materials.MaterialYellowGreen}
        position={[-11.625, 1.076, -8.747]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-14.044, 0.772, -7.742]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-10.647, 0.682, -11.812]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-10.294, 0.772, -7.895]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-14.073, 2.158, -9.412]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013002'].geometry}
        material={materials.MaterialBlue}
        position={[-15.598, 1.076, -8.747]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front002'].geometry}
        material={materials.MaterialWhiteText}
        position={[-17.732, 0.772, -7.742]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.863, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back002'].geometry}
        material={materials.MaterialWhiteText}
        position={[-14.256, 0.682, -11.812]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right002'].geometry}
        material={materials.MaterialWhiteText}
        position={[-14.267, 0.772, -7.895]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper002'].geometry}
        material={materials.MaterialWhiteText}
        position={[-17.78, 2.158, -9.412]}
        scale={[0.906, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left001'].geometry}
        material={materials['MaterialWhiteText.001']}
        position={[-18.053, 0.772, -11.257]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
    </group>
  )
}

useGLTF.preload('/NastavniBlokUcionice4.glb')

