/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NastavniBlok2(props) {
  const { nodes, materials } = useGLTF('/NastavniBlok2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sprat1.geometry}
        material={materials['MaterialWhite.001']}
        position={[0, -0.012, 0]}
        scale={[1.684, 0.105, 1.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Citaonica.geometry}
        material={materials.MaterialBlue}
        position={[-0.182, 0.258, 1.075]}
        scale={[0.937, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CitaonicaBack001.geometry}
        material={materials['MaterialWhiteText.001']}
        position={[-1.688, 0.17, 0.757]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.162, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CitaonicaLeft001.geometry}
        material={materials['MaterialWhiteText.001']}
        position={[-0.673, 0.255, 1.6]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.242, 0.203, 0.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CitaonicaRight001.geometry}
        material={materials['Material.002']}
        position={[-0.597, 0.258, 0.557]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.195, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CitaonicaUpper001.geometry}
        material={materials['MaterialWhiteText.001']}
        position={[-0.662, 0.416, 1.066]}
        rotation={[-Math.PI, 0.354, -Math.PI]}
        scale={[0.313, 0.304, 0.304]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HodnikSkriptarnica001.geometry}
        material={materials['MaterialWhite.002']}
        position={[0.634, -0.013, -2.503]}
        scale={[0.699, 0.105, 0.369]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DugackiHodnik001.geometry}
        material={materials['MaterialWhite.003']}
        position={[0.682, -0.012, 2.587]}
        scale={[1, 0.105, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A1.geometry}
        material={materials.MaterialOrange}
        position={[-0.182, 0.258, 2.112]}
        scale={[0.937, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A2.geometry}
        material={materials.MaterialOrange}
        position={[-0.182, 0.258, 4.462]}
        scale={[0.937, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A3.geometry}
        material={materials.MaterialOrange}
        position={[0.229, 0.258, 6.19]}
        scale={[0.937, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A4.geometry}
        material={materials['MaterialOrange.001']}
        position={[-2.121, 0.258, 6.19]}
        scale={[0.937, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DugackiHodnik002.geometry}
        material={materials['MaterialWhite.004']}
        position={[-1.469, -0.012, 2.587]}
        scale={[1, 0.105, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DugackiHodnik003.geometry}
        material={materials['MaterialWhite.005']}
        position={[1.109, -0.012, 2.587]}
        scale={[1, 0.105, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DugackiHodnik004.geometry}
        material={materials['MaterialWhite.006']}
        position={[1.109, -0.012, 5.039]}
        scale={[1, 0.105, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR0.geometry}
        material={materials.MaterialOrange}
        position={[1.128, 0.258, -0.771]}
        scale={[0.937, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR1.geometry}
        material={materials.MaterialOrange}
        position={[1.128, 0.258, 0.229]}
        scale={[0.937, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR2.geometry}
        material={materials.MaterialOrange}
        position={[1.128, 0.258, 1.229]}
        scale={[0.937, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR3.geometry}
        material={materials.MaterialOrange}
        position={[1.128, 0.258, 2.229]}
        scale={[0.937, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR4.geometry}
        material={materials.MaterialOrange}
        position={[1.128, 0.258, 4.435]}
        scale={[0.937, 0.153, 0.401]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR5.geometry}
        material={materials.MaterialOrange}
        position={[1.128, 0.258, 5.231]}
        scale={[0.937, 0.153, 0.401]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR6.geometry}
        material={materials.MaterialOrange}
        position={[1.128, 0.258, 6.154]}
        scale={[0.937, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NastavnickiKlub.geometry}
        material={materials['MaterialBlue.014']}
        position={[0.045, 0.258, -0.774]}
        scale={[0.937, 0.153, 0.517]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CitaonicaFront.geometry}
        material={materials['MaterialWhiteText.002']}
        position={[0.38, 0.17, 1.535]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[-0.248, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NastavnickiKlubRight.geometry}
        material={materials['Material.003']}
        position={[-0.547, 0.258, -1.297]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.195, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NastavnickiKlubLeft.geometry}
        material={materials['Material.004']}
        position={[-0.495, 0.258, -0.851]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[-0.199, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NastavnickiKlubFront.geometry}
        material={materials['MaterialWhiteText.003']}
        position={[0.693, 0.186, -0.868]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[-0.223, 0.211, 0.211]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NastavnickiKlubUpper.geometry}
        material={materials['Material.005']}
        position={[-0.542, 0.413, -1.084]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.195, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NastavnickiKlubBack.geometry}
        material={materials['MaterialWhiteText.004']}
        position={[-1.685, 0.186, -1.277]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={0.211}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A1Front.geometry}
        material={materials['MaterialWhiteText.005']}
        position={[0.38, 0.17, 3.134]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[-0.248, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A2Front.geometry}
        material={materials['MaterialWhiteText.006']}
        position={[0.38, 0.17, 5.181]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[-0.248, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A3Front.geometry}
        material={materials['MaterialWhiteText.007']}
        position={[0.38, 0.17, 7.06]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[-0.248, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A1Upper.geometry}
        material={materials['MaterialWhiteText.008']}
        position={[-0.61, 0.416, 2.539]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.313, 0.304, 0.304]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A2Upper.geometry}
        material={materials['MaterialWhiteText.009']}
        position={[-0.558, 0.416, 4.621]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.313, 0.304, 0.304]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A3Upper.geometry}
        material={materials['MaterialWhiteText.010']}
        position={[-0.558, 0.416, 6.448]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.313, 0.304, 0.304]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A4Upper.geometry}
        material={materials['MaterialWhiteText.011']}
        position={[-2.362, 0.416, 6.448]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.313, 0.304, 0.304]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR0Front.geometry}
        material={materials['MaterialWhiteText.012']}
        position={[1.691, 0.17, -0.51]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[-0.248, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR1Front.geometry}
        material={materials['MaterialWhiteText.013']}
        position={[1.691, 0.17, 0.472]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[-0.248, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR2Front.geometry}
        material={materials['MaterialWhiteText.014']}
        position={[1.691, 0.17, 1.433]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[-0.248, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR3Front.geometry}
        material={materials['MaterialWhiteText.015']}
        position={[1.691, 0.17, 2.461]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[-0.248, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR4Front.geometry}
        material={materials['MaterialWhiteText.016']}
        position={[1.691, 0.17, 4.661]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[-0.248, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR5Front.geometry}
        material={materials['MaterialWhiteText.017']}
        position={[1.691, 0.17, 5.455]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[-0.248, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR6Front.geometry}
        material={materials['MaterialWhiteText.018']}
        position={[1.691, 0.17, 6.56]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[-0.248, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR6Back.geometry}
        material={materials['MaterialWhiteText.019']}
        position={[1.321, 0.17, 6.085]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.221, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR5Back.geometry}
        material={materials['MaterialWhiteText.020']}
        position={[1.321, 0.17, 5.021]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.221, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR4Back.geometry}
        material={materials['MaterialWhiteText.021']}
        position={[1.321, 0.17, 4.276]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.221, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR3Back.geometry}
        material={materials['MaterialWhiteText.022']}
        position={[1.321, 0.17, 2.019]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.221, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR2Back.geometry}
        material={materials['MaterialWhiteText.023']}
        position={[1.321, 0.17, 1.033]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.221, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR1Back.geometry}
        material={materials['MaterialWhiteText.024']}
        position={[1.321, 0.17, 0.03]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.221, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR0Back.geometry}
        material={materials['MaterialWhiteText.025']}
        position={[1.321, 0.17, -0.934]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.221, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR0Upper.geometry}
        material={materials['MaterialWhiteText.026']}
        position={[1.522, 0.416, -0.739]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.25, 0.243, 0.243]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR1Upper.geometry}
        material={materials['MaterialWhiteText.027']}
        position={[1.522, 0.416, 0.247]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.25, 0.243, 0.243]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR2Upper.geometry}
        material={materials['MaterialWhiteText.028']}
        position={[1.522, 0.416, 1.208]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.25, 0.243, 0.243]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR3Upper.geometry}
        material={materials['MaterialWhiteText.029']}
        position={[1.522, 0.416, 2.212]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.25, 0.243, 0.243]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR4Upper.geometry}
        material={materials['MaterialWhiteText.032']}
        position={[1.522, 0.416, 4.443]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.25, 0.243, 0.243]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR5Upper.geometry}
        material={materials['MaterialWhiteText.033']}
        position={[1.522, 0.416, 5.238]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.25, 0.243, 0.243]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR6Upper.geometry}
        material={materials['MaterialWhiteText.034']}
        position={[1.522, 0.416, 6.323]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.25, 0.243, 0.243]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR6Left.geometry}
        material={materials['MaterialWhiteText.035']}
        position={[1.356, 0.17, 6.998]}
        rotation={[1.579, 0, -Math.PI]}
        scale={[-0.157, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR3Left.geometry}
        material={materials['MaterialWhiteText.036']}
        position={[1.356, 0.17, 2.751]}
        rotation={[1.579, 0, -Math.PI]}
        scale={[-0.157, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR0Right.geometry}
        material={materials['MaterialWhiteText.037']}
        position={[1.67, 0.17, -1.293]}
        rotation={[1.579, 0, -Math.PI]}
        scale={[0.182, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A3Left.geometry}
        material={materials['MaterialWhiteText.038']}
        position={[-1.086, 0.17, 7.222]}
        rotation={[1.579, 0, -Math.PI]}
        scale={[-0.211, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A4Left.geometry}
        material={materials['MaterialWhiteText.039']}
        position={[-2.896, 0.17, 7.222]}
        rotation={[1.579, 0, -Math.PI]}
        scale={[-0.211, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AR4Right.geometry}
        material={materials['MaterialWhiteText.040']}
        position={[1.67, 0.17, 4.026]}
        rotation={[1.579, 0, -Math.PI]}
        scale={[0.182, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A1Back.geometry}
        material={materials['MaterialWhiteText.041']}
        position={[-1.688, 0.17, 2.045]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.199, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A2Back.geometry}
        material={materials['MaterialWhiteText.042']}
        position={[-1.424, 0.17, 4.212]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.199, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A4Back.geometry}
        material={materials['MaterialWhiteText.043']}
        position={[-3.321, 0.17, 6.005]}
        rotation={[Math.PI / 2, -0.009, Math.PI / 2]}
        scale={[0.199, 0.235, 0.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair018.geometry}
        material={materials.MaterialCyan}
        position={[-1.625, -0.171, -0.597]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair019.geometry}
        material={materials.MaterialCyan}
        position={[-1.575, -0.15, -0.597]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair020.geometry}
        material={materials.MaterialCyan}
        position={[-1.525, -0.12, -0.597]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair021.geometry}
        material={materials.MaterialCyan}
        position={[-1.475, -0.09, -0.597]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair022.geometry}
        material={materials.MaterialCyan}
        position={[-1.425, -0.06, -0.597]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair023.geometry}
        material={materials.MaterialCyan}
        position={[-1.375, -0.03, -0.597]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair024.geometry}
        material={materials.MaterialCyan}
        position={[-1.325, 0, -0.597]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair025.geometry}
        material={materials.MaterialCyan}
        position={[-1.275, 0.03, -0.597]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair026.geometry}
        material={materials.MaterialCyan}
        position={[-1.225, 0.06, -0.597]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair027.geometry}
        material={materials.MaterialCyan}
        position={[-1.625, -0.171, 0.298]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair028.geometry}
        material={materials.MaterialCyan}
        position={[-1.575, -0.15, 0.298]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair029.geometry}
        material={materials.MaterialCyan}
        position={[-1.525, -0.12, 0.298]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair030.geometry}
        material={materials.MaterialCyan}
        position={[-1.475, -0.09, 0.298]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair031.geometry}
        material={materials.MaterialCyan}
        position={[-1.425, -0.06, 0.298]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair032.geometry}
        material={materials.MaterialCyan}
        position={[-1.375, -0.03, 0.298]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair033.geometry}
        material={materials.MaterialCyan}
        position={[-1.325, 0, 0.298]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair034.geometry}
        material={materials.MaterialCyan}
        position={[-1.275, 0.03, 0.298]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair035.geometry}
        material={materials.MaterialCyan}
        position={[-1.225, 0.06, 0.298]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair044.geometry}
        material={materials['MaterialCyan.001']}
        position={[-1.714, 0.128, 5.525]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair043.geometry}
        material={materials['MaterialCyan.001']}
        position={[-1.764, 0.15, 5.525]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair042.geometry}
        material={materials['MaterialCyan.001']}
        position={[-1.814, 0.18, 5.525]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair041.geometry}
        material={materials['MaterialCyan.001']}
        position={[-1.864, 0.21, 5.525]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair040.geometry}
        material={materials['MaterialCyan.001']}
        position={[-1.914, 0.24, 5.525]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair039.geometry}
        material={materials['MaterialCyan.001']}
        position={[-1.964, 0.27, 5.525]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair038.geometry}
        material={materials['MaterialCyan.001']}
        position={[-2.014, 0.3, 5.525]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair037.geometry}
        material={materials['MaterialCyan.001']}
        position={[-2.064, 0.33, 5.525]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair036.geometry}
        material={materials['MaterialCyan.001']}
        position={[-2.114, 0.36, 5.525]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair053.geometry}
        material={materials['MaterialCyan.002']}
        position={[1.419, -0.179, 3.61]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair052.geometry}
        material={materials['MaterialCyan.002']}
        position={[1.419, -0.158, 3.56]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair051.geometry}
        material={materials['MaterialCyan.002']}
        position={[1.419, -0.128, 3.51]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair050.geometry}
        material={materials['MaterialCyan.002']}
        position={[1.419, -0.098, 3.46]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair049.geometry}
        material={materials['MaterialCyan.002']}
        position={[1.419, -0.068, 3.41]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair048.geometry}
        material={materials['MaterialCyan.002']}
        position={[1.419, -0.038, 3.36]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair047.geometry}
        material={materials['MaterialCyan.002']}
        position={[1.419, -0.008, 3.31]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair046.geometry}
        material={materials['MaterialCyan.002']}
        position={[1.419, 0.022, 3.26]}
        scale={[0.264, 0.037, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC_Stair045.geometry}
        material={materials['MaterialCyan.002']}
        position={[1.419, 0.052, 3.21]}
        scale={[0.264, 0.037, 0.041]}
      />
    </group>
  )
}

useGLTF.preload('/NastavniBlok2.glb')

