/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NastavniBlokUcionice5(props) {
  const { nodes, materials } = useGLTF('/NastavniBlokUcionice5.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.MaterialWhite}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017'].geometry}
        material={materials.MaterialYellowGreen}
        position={[-4.023, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-6.284, 0.772, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-2.29, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-5.299, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-2.692, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-6.279, 2.158, -0.801]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairBase.geometry}
        material={materials.MaterialGray}
        position={[-0.664, 1.076, -8.748]}
        scale={[0.331, 1, 0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair.geometry}
        material={materials.MaterialCyan}
        position={[-1.821, 0.197, -8.273]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair001.geometry}
        material={materials['MaterialCyan.001']}
        position={[-1.821, 0.397, -8.573]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair002.geometry}
        material={materials['MaterialCyan.002']}
        position={[-1.821, 0.597, -8.773]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair003.geometry}
        material={materials['MaterialCyan.003']}
        position={[-1.821, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle.geometry}
        material={materials['MaterialCyan.004']}
        position={[-1.821, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair005.geometry}
        material={materials['MaterialCyan.005']}
        position={[0.511, 1.5, -8.494]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair006.geometry}
        material={materials['MaterialCyan.006']}
        position={[0.511, 1.3, -8.694]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair007.geometry}
        material={materials['MaterialCyan.007']}
        position={[0.511, 1.1, -8.994]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle001.geometry}
        material={materials['MaterialCyan.008']}
        position={[-1.821, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle002.geometry}
        material={materials['MaterialCyan.009']}
        position={[0.642, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair004.geometry}
        material={materials['MaterialCyan.010']}
        position={[0.511, 1.7, -8.294]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairBase001.geometry}
        material={materials.MaterialGray}
        position={[13.321, 1.076, -2.718]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.15, 1, 0.273]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair008.geometry}
        material={materials.MaterialCyan}
        position={[13.846, 0.197, -2.939]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair009.geometry}
        material={materials['MaterialCyan.001']}
        position={[13.846, 0.397, -2.8]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair010.geometry}
        material={materials['MaterialCyan.002']}
        position={[13.846, 0.597, -2.707]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair011.geometry}
        material={materials['MaterialCyan.003']}
        position={[13.846, 0.797, -2.614]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle003.geometry}
        material={materials['MaterialCyan.004']}
        position={[13.846, 0.797, -2.614]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair012.geometry}
        material={materials['MaterialCyan.005']}
        position={[12.787, 1.5, -2.836]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair013.geometry}
        material={materials['MaterialCyan.006']}
        position={[12.787, 1.3, -2.743]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair014.geometry}
        material={materials['MaterialCyan.007']}
        position={[12.787, 1.1, -2.604]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle004.geometry}
        material={materials['MaterialCyan.008']}
        position={[13.846, 0.797, -2.614]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle005.geometry}
        material={materials['MaterialCyan.009']}
        position={[12.728, 0.797, -2.614]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair015.geometry}
        material={materials['MaterialCyan.010']}
        position={[12.787, 1.7, -2.929]}
        scale={[0.375, 0.156, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC.geometry}
        material={materials.MaterialPink}
        position={[3.447, 1.108, -9.805]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCFront.geometry}
        material={materials.MaterialWhiteText}
        position={[2.229, 0.805, -7.66]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.545, -0.398, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCBack.geometry}
        material={materials.MaterialWhiteText}
        position={[4.692, 0.715, -11.837]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.49, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCRight.geometry}
        material={materials.MaterialWhiteText}
        position={[5.519, 0.805, -8.234]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[2.063, 2.19, -9.137]}
        scale={[1.545, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?'].geometry}
        material={materials.MaterialOrange}
        position={[3.626, 1.108, -1.094]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-0.132, 0.805, 1.052]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.166, -0.398, -0.843]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[4.786, 0.715, -3.126]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.156, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[1.641, 0.805, -2.698]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[5.698, 0.805, 0.478]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[0.023, 2.19, -0.72]}
        scale={[1.118, 1, 1.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017001'].geometry}
        material={materials.MaterialOrange}
        position={[0.086, 1.076, -0.025]}
        scale={[0.853, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Left001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-1.857, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Right001'].geometry}
        material={materials.MaterialWhiteText}
        position={[0.75, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?001'].geometry}
        material={materials.MaterialOrange}
        position={[12.02, 1.108, -1.094]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Front001'].geometry}
        material={materials.MaterialWhiteText}
        position={[9.125, 0.805, 1.052]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.614, -0.398, -0.843]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Back001'].geometry}
        material={materials.MaterialWhiteText}
        position={[12.209, 0.715, -3.126]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.592, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Left001'].geometry}
        material={materials.MaterialWhiteText}
        position={[10.034, 0.805, -2.698]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Upper001'].geometry}
        material={materials.MaterialWhiteText}
        position={[9.361, 2.19, -1.239]}
        scale={[1.118, 1, 1.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?002'].geometry}
        material={materials.MaterialBlue}
        position={[16.703, 1.108, -1.094]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Front002'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.485, 0.805, 1.052]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.906, -0.398, -0.843]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Back002'].geometry}
        material={materials.MaterialWhiteText}
        position={[18.471, 0.715, -3.126]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.908, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Left002'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.718, 0.805, -2.698]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Right002'].geometry}
        material={materials.MaterialWhiteText}
        position={[18.775, 0.805, 0.148]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.29, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Upper002'].geometry}
        material={materials.MaterialWhiteText}
        position={[15.433, 2.19, -1.266]}
        scale={[1.118, 1, 1.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?004'].geometry}
        material={materials.MaterialBlue}
        position={[16.703, 1.108, -9.801]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Front004'].geometry}
        material={materials.MaterialWhiteText}
        position={[13.178, 0.805, -7.656]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.166, -0.398, -0.843]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Back004'].geometry}
        material={materials.MaterialWhiteText}
        position={[18.149, 0.715, -11.833]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.204, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Left004'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.718, 0.805, -11.406]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Right004'].geometry}
        material={materials.MaterialWhiteText}
        position={[18.775, 0.805, -8.633]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.29, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Upper004'].geometry}
        material={materials.MaterialWhiteText}
        position={[13.275, 2.19, -9.428]}
        scale={[1.118, 1, 1.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SS.geometry}
        material={materials.MaterialBlue}
        position={[6.354, 1.108, -1.094]}
        scale={[0.798, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSFront.geometry}
        material={materials.MaterialWhiteText}
        position={[5.765, 0.805, 1.052]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.744, -0.398, -0.886]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSBack.geometry}
        material={materials.MaterialWhiteText}
        position={[8.887, 0.715, -3.126]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.739, -2.321, -1.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSLeft.geometry}
        material={materials.MaterialWhiteText}
        position={[5.551, 0.805, -2.698]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSRight.geometry}
        material={materials.MaterialWhiteText}
        position={[7.191, 0.805, 0.478]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[6.523, 2.19, -1.168]}
        scale={[0.784, 0.716, 0.885]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SS001.geometry}
        material={materials.MaterialOrange}
        position={[6.354, 1.108, -9.812]}
        scale={[0.798, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSFront001.geometry}
        material={materials.MaterialWhiteText}
        position={[6.806, 0.805, -7.667]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.959, -0.398, -0.886]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSBack001.geometry}
        material={materials.MaterialWhiteText}
        position={[11.382, 0.715, -11.844]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.038, -2.321, -1.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSLeft001.geometry}
        material={materials.MaterialWhiteText}
        position={[5.551, 0.805, -11.416]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSRight001.geometry}
        material={materials.MaterialWhiteText}
        position={[7.191, 0.805, -8.241]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 0.798, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SSUpper001.geometry}
        material={materials.MaterialWhiteText}
        position={[6.653, 2.19, -9.458]}
        scale={[1.095, 1, 1.236]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013002'].geometry}
        material={materials.MaterialBlue}
        position={[-15.598, 1.076, -8.747]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front002'].geometry}
        material={materials.MaterialWhiteText}
        position={[-17.732, 0.772, -7.742]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.863, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back002'].geometry}
        material={materials.MaterialWhiteText}
        position={[-11.733, 0.682, -11.812]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right002'].geometry}
        material={materials.MaterialWhiteText}
        position={[-14.267, 0.772, -7.895]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper002'].geometry}
        material={materials.MaterialWhiteText}
        position={[-16.473, 2.158, -7.412]}
        scale={[0.906, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left001'].geometry}
        material={materials['MaterialWhiteText.001']}
        position={[-18.053, 0.772, -9.607]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015'].geometry}
        material={materials.MaterialOrange}
        position={[-14.154, 1.076, -0.025]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-15.757, 0.772, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-13.838, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-15.43, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.823, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-16.025, 2.158, -0.801]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Left002'].geometry}
        material={materials['MaterialWhiteText.002']}
        position={[-18.053, 0.772, -3.607]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015001'].geometry}
        material={materials.MaterialOrange}
        position={[-3.586, 1.076, -8.743]}
        scale={[0.852, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Front001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-7.652, 0.772, -7.739]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Back001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-3.496, 0.682, -11.817]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Left001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-4.862, 0.772, -10.519]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['015Upper001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-7.66, 2.158, -9.519]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013001'].geometry}
        material={materials.MaterialYellowGreen}
        position={[-9.068, 1.076, -8.747]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013003'].geometry}
        material={materials.MaterialYellowGreen}
        position={[13.707, 1.076, -0.017]}
        scale={[0.646, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Front003'].geometry}
        material={materials.MaterialWhiteText}
        position={[12.597, 0.772, 1.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.993, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Back003'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.064, 0.682, -1.178]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.958, -1.103, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Right003'].geometry}
        material={materials.MaterialWhiteText}
        position={[-7.736, 0.772, -7.895]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['013Upper003'].geometry}
        material={materials.MaterialWhiteText}
        position={[12.62, 2.152, 0.349]}
        scale={[0.993, 1, 1]}
      />
    </group>
  )
}

useGLTF.preload('/NastavniBlokUcionice5.glb')

