/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NastavniBlokUcionice2(props) {
  const { nodes, materials } = useGLTF('/NastavniBlokUcionice2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.MaterialWhite}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017'].geometry}
        material={materials.MaterialOrange}
        position={[-1.799, 1.076, -0.025]}
        scale={[3.438, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-3.915, 0.56, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.691, 1, 1.478]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[0.175, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-2.595, -1.103, -1.435]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-5.257, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 3.438, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[1.809, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 3.438, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['017Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-3.898, 2.158, -0.278]}
        scale={[2.691, 1, 1.685]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairBase.geometry}
        material={materials.MaterialGray}
        position={[-0.664, 1.076, -8.748]}
        scale={[0.331, 1, 0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair.geometry}
        material={materials.MaterialCyan}
        position={[-1.821, 0.197, -8.273]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair001.geometry}
        material={materials['MaterialCyan.001']}
        position={[-1.821, 0.397, -8.573]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair002.geometry}
        material={materials['MaterialCyan.002']}
        position={[-1.821, 0.597, -8.773]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair003.geometry}
        material={materials['MaterialCyan.003']}
        position={[-1.821, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle.geometry}
        material={materials['MaterialCyan.004']}
        position={[-1.821, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair005.geometry}
        material={materials['MaterialCyan.005']}
        position={[0.511, 1.5, -8.494]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair006.geometry}
        material={materials['MaterialCyan.006']}
        position={[0.511, 1.3, -8.694]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair007.geometry}
        material={materials['MaterialCyan.007']}
        position={[0.511, 1.1, -8.994]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle001.geometry}
        material={materials['MaterialCyan.008']}
        position={[-1.821, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairMiddle002.geometry}
        material={materials['MaterialCyan.009']}
        position={[0.642, 0.797, -8.973]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair004.geometry}
        material={materials['MaterialCyan.010']}
        position={[0.511, 1.7, -8.294]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.826, 0.156, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WC.geometry}
        material={materials.MaterialPink}
        position={[3.447, 1.108, -9.805]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCFront.geometry}
        material={materials.MaterialWhiteText}
        position={[2.229, 0.805, -7.66]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.545, -0.398, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCBack.geometry}
        material={materials.MaterialWhiteText}
        position={[4.692, 0.715, -11.837]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.49, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCRight.geometry}
        material={materials.MaterialWhiteText}
        position={[5.519, 0.805, -8.234]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WCUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[2.063, 2.19, -9.137]}
        scale={[1.545, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?'].geometry}
        material={materials.MaterialBlue}
        position={[3.626, 1.108, -1.094]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[2.457, 0.805, 1.052]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.545, -0.398, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[4.871, 0.715, -3.126]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.49, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[1.641, 0.805, -2.698]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[5.698, 0.805, 0.478]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[2.5, 2.19, -0.235]}
        scale={[1.545, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Svecana.geometry}
        material={materials.MaterialBlue}
        position={[7.473, 1.108, -9.815]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaFront.geometry}
        material={materials.MaterialWhiteText}
        position={[8.046, 0.805, -7.67]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.431, -0.398, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaBack.geometry}
        material={materials.MaterialWhiteText}
        position={[11.066, 0.715, -11.847]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.425, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaLeft.geometry}
        material={materials.MaterialWhiteText}
        position={[5.487, 0.805, -11.42]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaRight.geometry}
        material={materials.MaterialWhiteText}
        position={[9.545, 0.805, -8.244]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaUpper.geometry}
        material={materials.MaterialWhiteText}
        position={[8.236, 2.19, -9.147]}
        scale={[1.348, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Svecana001.geometry}
        material={materials.MaterialBlue}
        position={[-8.997, 1.108, -9.815]}
        scale={[1.974, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaFront001.geometry}
        material={materials.MaterialWhiteText}
        position={[-8.728, 0.805, -7.67]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1.431, -0.398, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaBack001.geometry}
        material={materials.MaterialWhiteText}
        position={[-6.404, 0.715, -11.847]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.425, -2.321, -1.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaRight001.geometry}
        material={materials.MaterialWhiteText}
        position={[-6.925, 0.805, -8.244]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaUpper001.geometry}
        material={materials.MaterialWhiteText}
        position={[-8.56, 2.19, -9.147]}
        scale={[1.348, 1, 2.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016'].geometry}
        material={materials.MaterialBlue}
        position={[-7.971, 1.076, -0.025]}
        scale={[2.355, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-9.411, 0.586, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.152, 1, 1.397]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-6.042, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-2.133, -1.103, -1.427]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Left'].geometry}
        material={materials.MaterialWhiteText}
        position={[-10.34, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 2.355, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-5.5, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 2.355, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-9.689, 2.158, -0.461]}
        scale={[2.483, 1.149, 1.861]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016002'].geometry}
        material={materials.MaterialOrange}
        position={[7.482, 1.076, -0.025]}
        scale={[1.834, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Front002'].geometry}
        material={materials.MaterialWhiteText}
        position={[6.361, 0.586, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.676, 1, 1.397]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Back002'].geometry}
        material={materials.MaterialWhiteText}
        position={[8.984, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.661, -1.103, -1.427]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Left002'].geometry}
        material={materials.MaterialWhiteText}
        position={[5.638, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.834, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Right002'].geometry}
        material={materials.MaterialWhiteText}
        position={[9.406, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.834, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Upper002'].geometry}
        material={materials.MaterialWhiteText}
        position={[6.145, 2.158, -0.461]}
        scale={[1.933, 1.149, 1.861]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016003'].geometry}
        material={materials.MaterialBlue}
        position={[11.454, 1.076, -0.025]}
        scale={[1.834, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Front003'].geometry}
        material={materials.MaterialWhiteText}
        position={[10.333, 0.586, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.676, 1, 1.397]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Back003'].geometry}
        material={materials.MaterialWhiteText}
        position={[12.956, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.661, -1.103, -1.427]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Left003'].geometry}
        material={materials.MaterialWhiteText}
        position={[9.61, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.834, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Right003'].geometry}
        material={materials.MaterialWhiteText}
        position={[13.378, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.834, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Upper003'].geometry}
        material={materials.MaterialWhiteText}
        position={[10.116, 2.158, -0.461]}
        scale={[1.933, 1.149, 1.861]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016004'].geometry}
        material={materials.MaterialOrange}
        position={[16.552, 1.076, -0.025]}
        scale={[1.834, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Front004'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.409, 0.586, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.676, 1, 1.397]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Back004'].geometry}
        material={materials.MaterialWhiteText}
        position={[18.054, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.661, -1.103, -1.427]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Left004'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.708, 0.772, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.834, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Right004'].geometry}
        material={materials.MaterialWhiteText}
        position={[18.77, 0.516, 0.443]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.521, 2.961, 1.709]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Upper004'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.402, 2.158, -0.461]}
        scale={[1.933, 1.149, 1.861]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016005'].geometry}
        material={materials.MaterialOrange}
        position={[16.552, 1.076, -8.744]}
        scale={[1.834, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Front005'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.822, 0.586, -7.74]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.676, 1, 1.397]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Back005'].geometry}
        material={materials.MaterialWhiteText}
        position={[17.58, 0.682, -11.818]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.661, -1.103, -1.427]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Left005'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.708, 0.772, -10.52]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.783, 1.834, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Right005'].geometry}
        material={materials.MaterialWhiteText}
        position={[18.77, 0.516, -8.638]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.521, 2.961, 1.709]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Upper005'].geometry}
        material={materials.MaterialWhiteText}
        position={[14.607, 2.158, -9.18]}
        scale={[1.933, 1.149, 1.861]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016001'].geometry}
        material={materials['MaterialOrange.001']}
        position={[-15.584, 1.076, -0.025]}
        scale={[2.355, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Front001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-15.597, 0.586, 0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.152, 1, 1.397]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Back001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.265, 0.682, -3.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-2.133, -1.103, -1.427]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Left001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-18.018, 0.614, -2.313]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.682, 4.065, 1.726]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Right001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-13.113, 0.772, 0.827]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 2.355, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['016Upper001'].geometry}
        material={materials.MaterialWhiteText}
        position={[-15.907, 2.158, -0.461]}
        scale={[2.483, 1.149, 1.861]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018'].geometry}
        material={materials['MaterialOrange.001']}
        position={[-14.072, 1.076, -8.748]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018Front'].geometry}
        material={materials.MaterialWhiteText}
        position={[-16.755, 0.602, -7.732]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.616, 1.31, 1.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018Back'].geometry}
        material={materials.MaterialWhiteText}
        position={[-14.306, 0.566, -11.859]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1.291, -1.487, -1.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018Right'].geometry}
        material={materials.MaterialWhiteText}
        position={[-12.74, 0.772, -7.885]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 1.269, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['018Upper'].geometry}
        material={materials.MaterialWhiteText}
        position={[-17.05, 2.158, -8.908]}
        scale={[2.034, 2.049, 2.049]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SvecanaLeft001.geometry}
        material={materials.MaterialWhiteText}
        position={[-18.063, 0.805, -11.048]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.646, 1.974, 1]}
      />
    </group>
  )
}

useGLTF.preload('/NastavniBlokUcionice2.glb')